### ISSUE TITLE
Can't Party in a LAN world

### ISSUE THREAD

**Issue by Subprimal** [Funwayguy/BetterQuesting#112]
Hello there, Looking to just find out if there's a working version for parties, Just updated our Project Ozone 2 that uses 1.90, and neither me or my girlfriend could add each other to a party in the book.

**Comment by Funwayguy** [comment]
version '1.90' of what exactly? My builds have 3 numbers all of which are important in fixing this if there is an issue

**Comment by Subprimal** [comment]
Sorry about that, I mean't to say 2.0.190 On 1.7.10 MC single player with LAN

**Comment by Funwayguy** [comment]
I'll take a look at it tomorrow. Probably has something to do with the wierd way Minecraft handles UUIDs through LAN

**Comment by Subprimal** [comment]
Thanks a lot!

**Comment by Peeebo** [comment]
This mod seems to be used with "Better Questing-Quest Book" frequently.  With Project Ozone 2 :Reloaded relying on both. I saw your post and updated to fix the "not being able to party with other players" issue. I Admin a Akliz server and my players are having this problem.  I tried updating your mod but got sideswiped when the quest book mod lost its mind and crashed my server. Just a bunch of info I thought you might need in case the issue was not on your end.  Great mod BTW.

**Comment by Funwayguy** [comment]
@Peeebo ~~Quest Book hasn't updated yet to support 2.x.x builds and I won't be doing support for 1.x.x. Sorry but you're going to be stuck with that problem. I am however in contact with Cazador and Drethic so I'll try and get the pack to transition to 2.x.x as smoothly as possible (might come at a cost of reset progression though).~~ Apparently PO2 has BQ2 already, can I get that crash report on a separate thread?

@Subprimal I think I've tracked down the issue and by the looks of it I made a really dumb oversight. Hopefully should have a fix out within a day or so (if everything goes well that is)

EDIT: Updates sent out to Curse. Should be downloadable shortly

**Comment by Peeebo** [comment]
It was just a simple missing mod error. I updated to your new build and the crash issue was with Quest Book. 
PM Description: Exception in server tick loop

Missing Mods:
	betterquesting : [1.0.23,

This one was NOT on your end. I was just giving you some more info in case this was what people using PO2 were experiencing.
