### ISSUE TITLE
Major performance Issues - 1 TPS

### ISSUE THREAD

**Issue by Sir-Will** [Funwayguy/BetterQuesting#123]
Can this be improved?

(BetterQuesting-2.0.190)
![](http://i.imgur.com/QIFu9z9.jpg)

**Comment by Sir-Will** [comment]
Getting worse...

![](http://i.imgur.com/lWHiygY.jpg)
![](http://i.imgur.com/2WSnEX6.jpg)
![](http://i.imgur.com/M74Dc56.jpg)

**Comment by Funwayguy** [comment]
Quests update once per tick per person (they have to for various reasons). How many 'active' (unlocked but incomplete) quests do you currently have at once? Also how many tasks of what type to do have attached to them?

**Comment by Sir-Will** [comment]
Where can I check this?

**Comment by Slind14** [comment]
Is there any progress on this issue. We had to throw out better questing and move back to hqm, due to the intensity of this issue.

**Comment by Funwayguy** [comment]
I have a solution in mind but it's not a quick fix by any means. Im also still not exactly sure how you caused so much performance overhead. I'm gussing you had way too many quests open at the same time or one of the task types is broken. Can you post that QuestDatabase.json for me to look at?

**Comment by DarkBlade177** [comment]
I am scare about this problem so i will wait to put this mod on my server...

Anyway... @Slind14 do you have a HQM (mine 1.7.10) modified version without the `ArrayIndexOutOfBoundsException` issue ?

I found some forks over the github but i have no idea how to compile a mod, or if they work T,T

**Comment by Funwayguy** [comment]
You know, after seeing you other issue with 1.3K players on a single server, I get the feeling that's heavily contributing to this. I'm going to be rewriting how quests process themselves so that things can be cached and multi-threaded.

**Comment by Slind14** [comment]
Would it be possible to only load the required data?

No need to process data from offline players and teams.

On 25 Jan 2017 07:30, "Funwayguy" <notifications@github.com> wrote:

You know, after seeing you other issue with 1.3K players on a single
server, I get the feeling that's heavily contributing to this. I'm going to
be rewriting how quests process themselves so that things can be cached and
multi-threaded.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Funwayguy/BetterQuesting/issues/123#issuecomment-275030139>,
or mute the thread

**Comment by EverNife** [comment]
Just for me to know... how many players do your servers have online at the same time?

**Comment by Funwayguy** [comment]
I've made some changes in builds 2.0.212 and 2.3.213 to how quests and task are ticked with some additional caching which which may help with server performance (1.3K players is still excessive though)
