### ISSUE TITLE
I get a warning when checking version is diabled

### ISSUE THREAD

**Issue by Dream-Master** [Funwayguy/BetterQuesting#127]
I get a warning when checking version is diabled in the cfg file.

I am using the  Better Questing 1 astest Version

Log:
https://gist.github.com/Dream-Master/d151ca7bd92152b3566672fa9eda9bbc

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/22126836/a0d520f4-de99-11e6-8444-6a972f8981da.png)

**Comment by trismegistis** [comment]
;o

**Comment by Funwayguy** [comment]
1) The check is still made in the background for various reasons, hence why the option is 'hide' not 'disable'. Serious errors in the check will still be reported to console and chat so the user can report it to me like so.
2) The reasons the check is failing (for a lot of my mods) is because the build service I was using was deprecated without warning taking all my version tracking files with it.
3) Better Questing and Standard Expansion already have updates to temporarily remove the tracker while I sort out migration to a new service.
