### ISSUE TITLE
Detect / on pickup not triggering quest updates

### ISSUE THREAD

**Issue by JonathanCSmith** [Funwayguy/BetterQuesting#130]
Following on from #128 (see that for background), we reset the quests and now are attempting to redo them with whatever we have on hand. The only way we have managed to get quests to trigger is re crafting. Occasionally it will detect a shift click into inventory of an existing item, but detect does not work at all.

**Comment by Ryukossei** [comment]
I am also having this same issue in my game as well. On My brothers server, him and his freind have completed a few quests (not alot just a few) and when I was added, I was unable to gain items fro them completed those quests. I cant even progress into the book further so that I may have a chance to catch up with them. It shows that the quest is completed in the overview part of it, yet when I go into the specific quest, it says it is incomplete and will not allow me to complete the quest. We have tried resetting the quest log, deleting player data and restarting, and a few other things. Nothing seems to work. We are at a loss of what to do now.

**Comment by Funwayguy** [comment]
@JonathanCSmith Not a bug. Crafting tasks exclusively require the player to 'craft' the required item. What you're thinking of is a retrieval task which only requires you to have said items.

@Ryukossei That actually isn't a bug either. BQ doesn't let players claim rewards in completed quests if they were not in the party at the time. This prevents people from exploiting progression by partying up with people who already did all the work. You'd have to reset everyone's progress and do it all over again if you wanted to reclaim those rewards (or just spawn them in).
