### ISSUE TITLE
Crafting Quests don't seem to sync properly in Multiplayer.

### ISSUE THREAD

**Issue by byang77** [Funwayguy/BetterQuesting#131]
Playing on PO2 2.2.3, with version 2.0.208. Detect/Submit quests seem to sync okay but the crafting task is not. First sieve crafting quest is not synced between my friend and I.

**Comment by JonathanCSmith** [comment]
I believe this is directly related to #128 and #130. I actually think the error lies in the implementation in https://github.com/Funwayguy/StandardQuestingPack/tree/1.7.10 rather than here. Essentially for PO2 nearly all of the early quests seem to be crafting (not sure how to identify this from the tooltip - but I didn't look too hard) which are not syncing correctly.

I am going to add another issue to the above repo just in case but forgive me if I am wrong!

**Comment by Funwayguy** [comment]
This appears to only be a visual bug it seems. Internally the quests should still work for parties but I forgot to show combined progress in the task UI and instead only show the individual user's. @JonathanCSmith was also correct in pointing out that it has to do with the expansion and not the base mod. Funnily enough, turns out crafting isn't the only task type with this problem.
