### ISSUE TITLE
[1.10] Multiplayer Editing Issue

### ISSUE THREAD

**Issue by sdholcomb** [Funwayguy/BetterQuesting#139]
Similar issue to #136 
I tested this out with a clean server to make sure it was not compatibility since it only occurs in multiplayer.

- Tasks and Rewards can't be removed when delete button hit in editor
- Rewards are not saved even though it will show the item at first after creation

I replicated the same quest in singleplayer and multiplayer involving the reward of a flower and these are the resulting files:

Multiplayer QuestDatabase.json
```json
"rewards": [
        {
          "rewards": [],
          "rewardID": "bq_standard:item",
          "index": 0
        }
      ]
```

Singleplayer QuestDatabase.json

```json
"rewards": [
        {
          "rewards": [
            {
              "id": "minecraft:red_flower",
              "Count": 1,
              "OreDict": "",
              "Damage": 1
            }
          ],
          "rewardID": "bq_standard:item",
          "index": 0
        }
      ]
```
I saw that you had a fix for the syncing in the builds for [1.7.10]. Maybe it is a similar issue.

**Versions:
BetterQuesting-2.3.213
StandardExpansion-2.3.124**

**Comment by Funwayguy** [comment]
Turns out I made a really dumb oversight in task/reward edits. Existing data was not being cleared and any new conflicting information would be ignored. Single player works because there's only one copy of the database but it wasn't necessarily 'working' correctly either. Definitely will get this fixed next update so thanks for the report.
