### ISSUE TITLE
Crash when non-op tries to click Add New, Add/Remove Quests, or Done within the edit scrren

### ISSUE THREAD

**Issue by Drethic** [Funwayguy/BetterQuesting#14]
We have no Quest Lines setup, and one quest that was setup clicking Add New by me.  When our quest maker is trying to add a quest line, quest, or exit through Done she disconnects from the server.  I've looked through the fml-client-latest log and could not find anything erroring out, but didn't know if this was permission based, or a bug.  We are running 1.0.18 and will try again with 1.0.19 when I finish the updates to the pack and make it live.

If this is permissions, is there a way to have the user get an error, and a way I can grant access through ForgeEssentials permission system?

**Comment by Funwayguy** [comment]
You are looking in the wrong file for the errors. The one you're looking for should simply be labelled 'latest.log'. I doubt it is a permission thing otherwise it would happen server side. I will need this log in order to pinpoint exactly the reason for the disconnect.

As for Forge Essentials support, I will only be using the vanilla OP levels. The power some of the quest rewards have for exploitation and permanent server damage (e.g. using hidden command rewards to circumvent permission limits) means there is no middle ground you could set anyway.

**Comment by Drethic** [comment]
I deopped myself and was able to reproduce the error.  It was in the server site fml-server-latest:
http://pastebin.com/pPexkBJx

You bring up a good point with only allowing OPs to use it.  Is there a specific level that would have access or would Level 1 be enough?

**Comment by Funwayguy** [comment]
I think any OP level has access to editors. On a side note I did locate the source of the error thanks to that log.

**Comment by Funwayguy** [comment]
Pushed out update 1.0.20 a little while ago which should fix this
