### ISSUE TITLE
Auto Claim Not Working

### ISSUE THREAD

**Issue by ghost** [Funwayguy/BetterQuesting#140]
I am using Forge 1.10.2-12.18.3.2221.  I updated to the latest Better Questing 2.3.213 and noticed that the autoClaim set to True is not working.  I am not automatically receiving the reward.  The quest triggers and I get the "Quest Completed".  I also tried BetterQuesting 2.3.211 and still not working.  I then tried version 2.3.209 and it IS working.  So something changed in the last  two version to stop my autoClaim to stop automatically give me the reward. 

Thanks for checking into this.

MCJediYoda

**Comment by Funwayguy** [comment]
It broke because I started caching active quests for ticking instead of ticking all of them for every player but in the process I forgot to handle some edge case functionality such as resetting repeatable quests and performing auto-claims. I am however fixing this up for the next update so it shouldn't be broken for too much longer
