### ISSUE TITLE
Interoperability with Tinkers' Construct

### ISSUE THREAD

**Issue by TinkerWorX** [Funwayguy/BetterQuesting#143]
In previous versions of BetterQuesting I have been able to create a Tinkers' Construct tool and then give it as a reward and the item would come out as a clone. This is not the case anymore. I was lucky to still have the unmodified quest from when it was working. If I compare the two quest rewards, it does appear that the nbt data has changed. I don't know if this is caused by Tinkers' Construct or if Better Questing is reading the information out wrong.

You can see the working and not working data [here](https://gist.github.com/TinkerWorX/109bc1ac00c676f806d416d46bc6cc19). I tried copying the working data into the quest manually, but that didn't work either, which perhaps points to Tinkers' Construct having changed something. I don't recall which version of Tinkers' Construct the quest worked with.

**Comment by Funwayguy** [comment]
Oh I think I see what I messed up. I should be able to get that update out sometime today or tomorrow

**Comment by Funwayguy** [comment]
Turns out I was wrong about my initial assumption. The 'working' copy is actually wrongly formatted to accurately be converted to item NBT tags (that's what the number suffixes are for). I'll double check in dev seeing as I have tinkers loaded in for testing already but from what I can gather between the two versions, the NBT structure on tools has changed slightly. Have you tried recreating the tools and reward from scratch?

**Comment by TinkerWorX** [comment]
Yea, both the tools and the rewards have been created from scratch. Like I mentioned, it's pure chance that I still had the nbt from the original quest in a different save.

**Comment by TheQKnight** [comment]
I am having an issue similar to this. I don't know if it is the same issue or not, but when I make a tinkers construct tool and set it as an item requirement to complete the quest (In game), it's nbt data is all screwed up. The tip of the tool is not the right color, and it just says "Pickaxe" instead of the actual name I gave it. It doesn't even have the same properties.

**Comment by asphaltbuffet** [comment]
Still seems to be a problem, any updates on this?
