### ISSUE TITLE
Object Submission Station can see hidden quests

### ISSUE THREAD

**Issue by evilmrhenry** [Funwayguy/BetterQuesting#149]
Minecraft 1.7.10
BQ 2.0.216

Repro:
1) Create a quest.
2) Remove the quest from all quest groups. There is now no way for a player to view it through the BQ UI.
3) Check the OSS. It's still visible in there.

I would expect quests that are not part of any quest group to also be hidden in the OSS.

**Comment by Funwayguy** [comment]
The ability for the OSS to 'see' a quest not in a quest line isn't really a bug but that does bring up an issue that IS a bug. The OSS should be adhering to the 'visibility' setting in a quest which it currently does not. Using that instead of simply removing it from all quest lines would be the proper way of hiding it from the OSS. I'll try and fix visibility for the next update

**Comment by Funwayguy** [comment]
Visibility fixed (when quests are explicitly marked as 'hidden')
