### ISSUE TITLE
[Request] Add "treat all crafting tasks as retrieval tasks" option.

### ISSUE THREAD

**Issue by codewarrior0** [Funwayguy/BetterQuesting#166]
Crafting tasks often do not award quest credit for various reasons, such as when alternate recipes for the items are provided by processing machines (a la GregTech) or when the item is crafted in a grid other than a Vanilla Crafting Table (such as the Logistics Request Table or Forestry Worktable). There needs to be a way for players to counter the misuse of crafting tasks by questbook authors other than by simply doing a search-and-replace on the quest files.

Or to state my honest opinion, crafting tasks should just be removed from the mod entirely.

**Comment by Funwayguy** [comment]
I have no intention of making the Crafting Task work with auto-crafting machinery nor do I intend to hardcode support for every mod's crafting tables that don't properly fire Forge Crafting Events as they should (HQM hardcodes support if you want to know why it works for them).

I'm also not going to simply remove the task type because people get upset over it working for their preferred crafting method. It's up to pack developers to chose the task type that they feel is more appropriate and test it without assuming it will magically work on every block in the universe, not me.

**Comment by codewarrior0** [comment]
Out of three BQM packs I've played - Project Ozone, New Horizons, Forever Stranded - all three of them had many issues related to quests having Crafting Tasks not awarding credit. In some cases because I used the "wrong" crafting grid, or because I used an Assembling Machine to save resources, or because I crafted something "too early" and didn't get credit for it. Are you saying all three pack authors are at fault here? 

Are you not at fault for making it this easy for them to do their jobs poorly?

**Comment by Claycorp** [comment]
Where to start.... Geez. So much complaining over mostly poor use of the mod. So let's start from the top!

1. If you are advanced enough to make something via a machine why add a crafting quest for it? Sounds like the quests were made backwards. Has nothing to do with the mod itself, Tell the pack dev!

2. Players don't need to do anything. If the pack dev did an oops or did something bad they need to be told. It's almost like reporting issues with mods! Who knew! Otherwise... don't play it if its sooo bad? (Psst. Has nothing to do with the mod)

3. Yup just remove it! Obviously people doing things incorrectly obviously means that it doesn't belong at all. You know... all those people that use it properly don't deserve the option to continue to use it. A+ on that thought process. (Still nothing to do with the mod!)

4. Lets add support for the 30 million crafting systems! Everyone knows it's eazy peazy and that they never change! Totally rad bro! (We can just ignore all the issues with the other people's code right?) 

5. You crafted something too early..? What does that even mean???? Oh I know. Someone didn't look at the book and follow whatever the dev set up (Likely made poorly) or you just don't care about the story or whatever the dev made. (You following a set of instructions poorly) (P.S. Still isn't the mods fault luv.)

Guess what! News is in and you sure seem to think the dev that made the mod is responsible for people using their ability (or inability in this case) to think logically about how to use it! We should get mad a Mojang for allowing their game to have such terrible TPS/FPS when I install 200 mods and use a 4k texture pack with every shader available cause they let me do it! Perhaps we should get mad at Oracle because they distribute and maintain Java and they allowed Mojang/Notch to make the game in the first place! SHAME ON ORACLE FOR ALLOWING THAT TERRIBLE MINECRAFT GAME TO EXIST! SHAME!


P.S. Craft everything packs that make a quest for every crafting thing under the sun and more don't count. Its poor use of the mod in my opinion. Is it wrong? No. Is it bad? No. It's just lazy and unoriginal but some people like it as an achievement system. Not my pie, Might be yours oh well. ¯\\_(ツ)_/¯ (or not I really don't care.)

**Comment by Cazadorsniper** [comment]
I use crafting tasks where I find it appropriate.

**Comment by Funwayguy** [comment]
...aaaand with that conclusive final answer I think I'm going to lock this thread now
