### ISSUE TITLE
[Major Issue] OSS doesn't work on multiplayer

### ISSUE THREAD

**Issue by DV666** [Funwayguy/BetterQuesting#177]
Hi Funwayguy !

I have a big trouble with the OSS on my server : he didn't work :(
I have some grindy quests so it's very annoying to dump like 100.000 wheats :D

The issue is very simple : OSS don't detect any quests on multiplayer but works perfectly on SSP.

Here's a screenshoot about that :

[Bug OSS : no quests available](http://img4.hostingpics.net/pics/37100920170313175055.png)

Thanks in advance to fix the issue asap.... :]

_DV_

**Comment by shank3001** [comment]
I am having the same issue with Forever Stranded on a server. I have to pull the server world down into single player in order to use the OSS.

**Comment by nzle** [comment]
same issue here on Forever Stranded.

**Comment by stripez79** [comment]
Same Issue here, and also running forever stranded. I tried updating the pack to the newest version at the moment (1.8.7.1) but it's just like the picture above. I can't select any quests or select dirt or anything..
Kinda annoying since I have to submit 1.000.000 dirt to get the job done. Hoping for a solution

**Comment by Redlotus99** [comment]
Seems Im having the same issue in 1.10.2 latest version of BQ

**Comment by AndrewR73** [comment]
I am currently running the server version of Forever Stranded (v1.8.9.1) -- the latest version available. The pack currently has Better Questing v2.3.225 (and Better Questing Triggerer v0.9).

The Object Submission Station is *not* working. I have been playing for near three months now, and regardless the updates by the pack creator, the OSS has *never* worked. The pack creator says he is unable to determine any problems on his end.

Here is a screenshot of the OSS showing no quests available, clicking the buttons do nothing, the green check-mark is not clickable, etc.:
https://cdn.discordapp.com/attachments/180022226790121472/307783790988623872/unknown.png

I will be happy to provide any files, logs, etc. needed but please FIX this!

**Comment by CiaranKennedy** [comment]
I'm going to try bumping this issue as we are also experiencing it on our servers.

**Comment by Funwayguy** [comment]
I'm aware of it, I just haven't gone back to fix it because my dev workspace is in a mid rewrite to fix the abomination that is the GUI design. I'll see if I can split my workspace to do some legacy patches to get the OSS up and running again seeing as this is a common issue people seem to be having.

EDIT: Found the cause already. Looks like an easy fix so maybe today/tomorrow I can post a quick update

EDIT2: Updates posted to CurseForge with a fix. Let me know if that gets things working for you guys. Sorry about the wait.

**Comment by Anteater46** [comment]
Looks like the new version causes a server crash on startup.
Report:
https://pastebin.com/cZiKBAmT

**Comment by Funwayguy** [comment]
Accidentally left a bit of client code on the server side on that build. Already uploaded fixed versions to Curse Forge
