### ISSUE TITLE
No dynamic update bug

### ISSUE THREAD

**Issue by fa1ntl1ght** [Funwayguy/BetterQuesting#178]
Ok, i'll installed this mod and created some simple quests like submit a pickaxe or mine stone and found a bug: When clicking Detect/Submit button it not reloads the state of items like this:

Before clicking submit button:

Stone
0/1
INCOMPLETE

After clicking submit button:

Stone
0/1
INCOMPLETE

but quest is completed and it allows to get a reward!
The "COMPLETE" label only shows when closing and opening gui again.

What causes this bug?

**Comment by Funwayguy** [comment]
I intentionally changed it to not update the GUIs panels when updating quest data. This was a sudo-fix for repeatable tasks constantly resetting the panel contents/scroll. It's going to take me a while to fix the root cause of the updates breaking things (I know what it is though) and this was the least intrusive compromise I could make in the mean time.

**Comment by fa1ntl1ght** [comment]
> I intentionally changed it to not update the GUIs panels when updating quest data. This was a sudo-fix for repeatable tasks constantly resetting the panel contents/scroll. It's going to take me a while to fix the root cause of the updates breaking things (I know what it is though) and this was the least intrusive compromise I could make in the mean time.

Ok, thanks for fast answer!
