### ISSUE TITLE
Repeatable quests

### ISSUE THREAD

**Issue by YouCanNotKnow** [Funwayguy/BetterQuesting#186]
Im trying to make trades for items and i want the quest to be repeatable. I changed the repeattime on that quest to 10 and i completed the quest with the command to complete quests but the countdown starts at 00 then keeps going down in negatives (-01 -02 -03). How can i make repeatable quests?

**Comment by jordanasch** [comment]
I have no idea if there is a better way to do this YouCanNotKnow, but I have created repeatable quests by making at least 2 quests act as one.

For example.

1 Repeatable Quest =

Quest 1:
ID: 1
Reward: (Command Reward: bq_admin reset 2 VAR_NAME)
*Make sure that the command reward is set viaPlayer

Quest 2:
ID: 2
Reward: (Command Reward: bq_admin reset 1 VAR_NAME)
*Make sure that the command reward is set viaPlayer

This way quest 1 resets quest 2 and quest 2 resets quest 1, making them fully repeatable.


I hope that helps you, but I'm running into another problem that I am not sure if it is caused by make repeatable quests like this, I sometimes can claim multiple rewards from one completion of a quest. And I don't think having a quest reset it self is very reliable but you could try it.

**Comment by evilmrhenry** [comment]
I think this is a bug with the newest version. I came here to post this, but a repeatable quest in my pack stopped working, with the same negative cooldown.

**Comment by Funwayguy** [comment]
Automatic quest logic such as repeat resets do not occur in edit mode. I intentionally disabled this last update because the resets would mess up the editors when people were in the middle of edits.

**Comment by evilmrhenry** [comment]
I wasn't in edit mode.

**Comment by evilmrhenry** [comment]
OK, figured out what I was doing wrong. I was in edit mode, because I never actually did a default save afterwards. The proper structure is
/bq_admin edit (turning it on)
Make your change
/bq_admin edit (turning it off)
/bq_admin default save
I'm not really happy about the lack of feedback with this, or the fact that I can apparently be in edit mode without the ability to actually edit quests while I'm in survival mode, but at least things work now.

**Comment by evilmrhenry** [comment]
This caught me again. Can you put a big EDIT MODE ON marking somewhere?

**Comment by Funwayguy** [comment]
Considering the number of people who keep forgetting about it, I'll probably add it in one of the next few updates. Need to finish rewriting the databases I've already ripped up first
