### ISSUE TITLE
Images not displaying on linux system

### ISSUE THREAD

**Issue by GreatOrator** [Funwayguy/BetterQuesting#190]
So weird bug.  Verified images do exist in the proper folders but in-game they will not display and you get the dreaded pink/black images when not found.  In the log this is what comes up:

[18:15:50] [Client thread/WARN]: Failed to load texture: tolkiencraft:textures\gui\main_title.png
java.io.FileNotFoundException: tolkiencraft:textures\gui\main_title.png
at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68) ~[bww.class:?]
at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[bxi.class:?]

again, this is on a linux system that this is happening from the report.

**Comment by Mrbinaer** [comment]
@GreatOrator I had that issue with your TolkienCraft III Modpack. 
While digging through the config files i noticed backslashes rather than slashes (which are used in linux for path names).

For example in **./config/betterquesting/DefaultQuests.json**: 
`"home_image": "tolkiencraft:textures\\gui\\main_title.png",`

which should be:
`"home_image": "tolkiencraft:textures/gui/main_title.png",`

I changed the following files to fix the missing images:

- **./config/betterquesting.cfg**
- **./config/betterquesting/DefaultQuests.json**
- **./saves/world/betterquesting/QuestDatabase.json**

Thank you for the great pack by the way. :)
