### ISSUE TITLE
[Suggestion] Pressing button R will show the craft of required item

### ISSUE THREAD

**Issue by ircmaan** [Funwayguy/BetterQuesting#221]
SUBJ. Like in HQM book 17.10.
It will be great.
Now it is very uncomfortable.
Thanx anyway for great mod.

**Comment by AlvinasLT** [comment]
Greetings from Lithuania. Thanks for the mod, but this post really affects the problem topic. It would be great to fix it.

**Comment by 0vendetta0** [comment]
It will be great, good luck from Russia.

**Comment by CTEIIAWKA** [comment]
YES, YES, YES. It will be great. Hello from Russia.

**Comment by Yasha93** [comment]
Hi, it would be nice if you added it, Thank you for your work, and look forward to what comes next

**Comment by EverNife** [comment]
Hello from Brazil  : D 

But... really supecious all these countries asking for this subject at the same time :D, and created at the same day, convenient ^^

![fry- medium](https://user-images.githubusercontent.com/11357801/29007175-f2cf54de-7ad3-11e7-88f3-8bc087eb6646.jpg)

But it's a good implementation though. But i think it will need to wait the Issue https://github.com/Funwayguy/BetterQuesting/issues/163

**Comment by ircmaan** [comment]
We are from one server :)
Our friend will make modepack with new BQ :)
Thanx

**Comment by Funwayguy** [comment]
IT'S A CONSPIRACY *runs around flailing*

Anyway, I probably won't be implementing this anytime soon mostly because a lot of the GUI related code in the current releases has already has been superseded by new stuff I've written for version 3.x.x. I can't give you an ETA on when that version will be released however as there is still a huge amount of work left to do on top of getting some of my IRL issues dealt with.
