### ISSUE TITLE
[Question] Got a 1.12 Version in the works?

### ISSUE THREAD

**Issue by Tylerun** [Funwayguy/BetterQuesting#227]
As the topic states just curious if you are working on a 1.12 version

**Comment by Funwayguy** [comment]
I kinda have a working version for 1.12 sitting in my development environment. Only problem with is that the new JSON registries broke items, blocks and their recipes. Trying to fix it all day annoyed me so I went back to working on the BQ3 rewrite/replacement for 1.10.2 and haven't touched it since
