### ISSUE TITLE
[1.7.10] Hidden quests not actually hidden

### ISSUE THREAD

**Issue by mensreaMC** [Funwayguy/BetterQuesting#244]
Not sure if this is intended behavior or not, but if something updates a hidden quest or it's completed, it appears. Version 2.0.233

**Comment by Thyriel** [comment]
Same in 1.12
Pretty nasty as deleting quests often results in weird behavior (new quests showing up where deleted quests where before) so there's no safe way to get rid of a quest without having one of these 2 problems

**Comment by mensreaMC** [comment]
I thought I remembered it working at one point. What makes you think it's a bug from deleting quests? I've had the issue with new quests showing up as well, but it stopped one day out of nowhere. I wonder if deleting the database and loading it from default would fix this...

EDIT: It didn't.

**Comment by Funwayguy** [comment]
Most of the time people accidentally use "remove" instead of "delete" when using the quest designer. This only removes it from the Quest Line but not from the active database. Another thing that may be misunderstood is that a quest can be "hidden" state can be one of many types and making them silencing them from notifications is another separate option.
