### ISSUE TITLE
Repeatable Quest Negative Timer [MC1.10.2]

### ISSUE THREAD

**Issue by Ockman** [Funwayguy/BetterQuesting#260]
I am building a questing modpack that features repeatable quests as a kind of "shop"
During my testing I discovered that repeatable quests do not count down to zero and unlock again, but rather count down infinitely into the negatives instead.
Only 2.3.234 and 3.3.237 of Better Questing for 1.10.2 have this issue. I tested all previous versions and they work fine.

This bug can be replicated with only (Forge 12.18.3.2511), (Better Questing 2.3.234), and (BQ - Standard Expansion 2.3.131) installed.

I assume the new alphas only have this issue because it was based off the version where the bug originates.

**Comment by evilmrhenry** [comment]
You're in edit mode.
Repeating my comment from a different issue:

OK, figured out what I was doing wrong. I was in edit mode, because I never actually did a default save afterwards. The proper structure is
/bq_admin edit (turning it on)
Make your change
/bq_admin edit (turning it off)
/bq_admin default save
I'm not really happy about the lack of feedback with this, or the fact that I can apparently be in edit mode without the ability to actually edit quests while I'm in survival mode, but at least things work now.

**Comment by Winddbourne** [comment]
I was having this problem too. Do you really have to save the quest to default in order to make it work? I was staying in edit mode to test and adjust my times, and I was working things out with a temporary place holder quest I had no intention of ever adding to the regular quest list. 

This is really unintuitive. Glad I looked the issue up rather than making a duplicate post.
