### ISSUE TITLE
[1.12.2] Crafting Task

### ISSUE THREAD

**Issue by CluelessPhil** [Funwayguy/BetterQuesting#276]
The crafting task doesn't detect when something is crafted like an oak chest. The retrieval task seems to work but that is not what i want!

## BQTrigger: 0.9C

**Comment by Nattehine** [comment]
I'm having the same problem in 1.12.2 with version 3.5.239 of the BQ mod. And yes, I'm definitely not in edit mode.

**Comment by EverNife** [comment]
Have you disabled 

> /bqm_admin edit

?


If not, try to turning it off!

**Comment by Funwayguy** [comment]
@evernife Nattehine specifically said they weren't in edit mode. The issue here is more likely to do with the outdated versions and the fixes that have been made since.

1) I don't support 2.x.x builds any more
2) The currently released beta versions are BQ 3.5.245 and SE 2.5.141

I have personally tested the Crafting Task on these versions and can confirm they appear to work fine when not in edit mode.

**Comment by EverNife** [comment]
Oh sorry, i just "Ctrl + C"  "Ctrl + V" the other 99 issues like this, my bad :D
