### ISSUE TITLE
If Quests are saved in the world how to release a pack with quests ?

### ISSUE THREAD

**Issue by AllInMods** [Funwayguy/BetterQuesting#279]

**Comment by Darkmega18** [comment]
I know this one!

run "bq_admin default save [desired name of pack]" to save the command into the configs menu.

then run "bq_admin default set [saved pack's name]" to set the quests as the default for all worlds.
yes you can have multiple, and yes you can switch them on the fly if you've got a server or something and you make quests as you go. but for the main effect of a pack of having a set questline, I've just got my questline saved as "modpackquestline" then got the default also set to it so that it is copied to each map.

Just make sure you save everytime you edit it to overwrite the pack defaults, then run bq_admin default load when loading up maps which had been using a previous version of the quests to update them for worlds like on servers and other singleplayer maps you didn't touch it for or it won't change.

**Comment by yujukitten** [comment]
Thanks DarkMega18 ^^ I was wondering this for awhile too!

**Comment by Darkmega18** [comment]
No problemo. :) Had to do some searching around when I first came across this predicament too. so happy to help.
