### ISSUE TITLE
[Question, BQ2->3] Does it save previous quests?

### ISSUE THREAD

**Issue by ElvenChaos** [Funwayguy/BetterQuesting#285]
I see the changelog entry `- This build will automatically update the existing quest formatting. This is NOT backwards compatible with BQ2!` and I don't 100% understand what is going on.

If I update BQ2 and the Standard Expansion to the BQ3 variants, does it update the previous quests to the new format, or will I need to re-write any previously written quests?

**Comment by Funwayguy** [comment]
Yes, it will update to current quests to the new format used in BQ3. It also makes a BQ2 format backup just in case. Trying to revert back to BQ2 without using the proper backups will result in lost data.

Due to the complexity and size of data involved, I can't guarantee that the conversion will be perfectly 1:1 however from what I've tested everything does seem to load and function just fine after conversion.

**Comment by ElvenChaos** [comment]
Thank you for clarifying!
