### ISSUE TITLE
[1.12.2] [BQ3] - Hardcore - BUG

### ISSUE THREAD

**Issue by bashduude** [Funwayguy/BetterQuesting#302]
If setting hardcore mode to true, quest book for some reason beginning to show all quests even if they have prerequisites, meaning you can start doing any quest in quest line.
Setting hardcore to false doing what is suppose to do. all reqired quests in quest line becoming hidden until reached. 
May be this will help. Its similar to edit mod. When turning hc to true quest line looks like if you have editor mode ON. 
so you can see all quests and enter any quest.
Can i get a fix please?
My pack is developed around hardcore. And i would like to use this mod for questing.
Can't continue developing my pack without this fix <3

**Comment by bashduude** [comment]
![1st](https://user-images.githubusercontent.com/32778092/36246347-74622a18-1240-11e8-9c60-f6fc2f8b2c45.png)
![2nd](https://user-images.githubusercontent.com/32778092/36246348-7545e866-1240-11e8-9390-57e804735502.png)

**Comment by bashduude** [comment]
Even dude above got a respond, rude.

**Comment by Funwayguy** [comment]
Really...

I do read bug reports and they are even sent to my phone. I'm not ignoring them, I just don't always respond. I barely respond to a bunch of these issues because a lot of them are to do with old code I've since deprecated anyway. This bug is from said old deprecated code.

I have looked into this, identified the bug and fixed it for the next build already but do keep in mind that this isn't necessarily stopping you from developing the pack so I wouldn't necessarily call it a critical bug. On top of that, I did mark these as beta builds so bugs are to be expected especially with the ongoing migration of the code. Speaking of which, I am literally working on replacing that screen right now anyway. I'm currently trying to get the zoom functions working again with the new systems hence why I haven't released the build yet.
