### ISSUE TITLE
Better Questing doesn't play that nice with Vivecraft

### ISSUE THREAD

**Issue by demonjacobs666** [Funwayguy/BetterQuesting#307]
![20180223180411_1](https://user-images.githubusercontent.com/36803146/36636036-b28c4cfc-196a-11e8-83ed-e3ac02144e5f.jpg)

just putting it out there to all relevant parties, there's a slight graphical issue when better questing combines with vivecraft

**Comment by demonjacobs666** [comment]
The version here is 2.5.236. I wonder what'll need to be transferred, since a base install of 3.5.239 won't have the quest data.

**Comment by Funwayguy** [comment]
Actually, BQ3 builds can load BQ2 data just fine. Doesn't work the otherway arround though. This screen has yet to be replaced in BQ3 but its due to be done very soon as soon as I get all the quest icons loaded into the frame. However, the cutout effect already got rewritten and is much more robust than it's old counterpart taking into account screenspace scalling and offsets which appears to be what broke here.

PS: I'm actually pretty amazed that, despite the graphical issue, it seems potentially usable. I don't have a Vive to debug this but I'd love to keep this functionality possible.

**Comment by demonjacobs666** [comment]
you were right, that was the problem and i think i moved the data to BQ3 correctly. as long as the modpack authors use BQ3, it's vivecraft-friendly
![20180224182026_1](https://user-images.githubusercontent.com/36803146/36637768-ded735fe-198f-11e8-8d4d-3d061d518d82.jpg)

**Comment by josiah-roberts** [comment]
In BetterQuesting-1.0.17 I can't click-and-drag in Vivecraft. Dunno if that's been fixed in newer versions. :confused:

**Comment by Funwayguy** [comment]
1.0.17?! You're over 2 years out of date. That's not even the most recent version for 1.7.10. Better Questing is only really usable with ViveCraft in BQ 3.x.x versions for 1.12.2 and I have no plans on back porting that anytime soon.
