### ISSUE TITLE
The Questbook Is Blank

### ISSUE THREAD

**Issue by KolasGames** [Funwayguy/BetterQuesting#308]
I'm currently playing in a mod pack and today I opened up the world and found that when I opened the better questing tab, the entire thing was just blank besides the menu. I don't think there are any other mods on the pack that affect the mod itself so I think this may be a glitch with the mod but I don't know, I've just seen others with a similar issue, but I wanna see if I can find a proper answer. I have no way of re-gathering the quests with commands either, the entire book is blank. The only way for me to fix this problem is to start a brand new world from the ground up, which I do not want to do at all

**Comment by Funwayguy** [comment]
Unfortunately there isn't a lot I can do to salvage lost data. Normally when this kind of thing happens its due to a mod that keeps refreshing the database. Can I as what version of the BetterQuesting you were using?

**Comment by KolasGames** [comment]
3.5.239 I believe. I'm using the Curse/Twitch app to play the mod pack so maybe it has something to do with their end but I'm not entirely sure. I already started a new world, just have to keep making sure I backup the game manually after every save now.

**Comment by MrNinja93** [comment]
Also had this happening on a server I admin, JSON just randomly breaks on the quest progress file occasionally on a server restart.

From a non modding perspective It looks like it's not saving correctly during the shutdown process or gets interrupted during the shutdown so only saves a partial copy of the questprogress.json.


Relevant Logs, only the single error being thrown when malformed questprogress is created from what I can see. (in fml-junk-earlystartup)

Also attached are the Questprogress from a backup and the broken one. 
https://gist.github.com/MrNinja93/becaf0808a3e8c55e95e2da70778e983

Forge: 14.23.2.2611
Minecraft: 1.12.2
BetterQuesting: 3.5.239

**Comment by mcsunnishines** [comment]
This has also happened to me, playing the homestead pack on ATlauncher.

**Comment by WesCook** [comment]
Just to add, Homestead doesn't use any auto-reloading mods.  I had read they can cause corruption before.

**Comment by Funwayguy** [comment]
May have finally figured out what may have caused this and why it doesn't throw any errors. Thought I fixed this a long time ago but seems my code refactoring may have brought it back. This took way longer than it should have for me to fix but I don't normally test with hundreds of quests and as you can probably imagine for \~90% of users this doesn't happen. Anyway, I have this fixed in build 251 which is just waiting me to finish an editor related GUI panel before I can send it to Curse.

EDIT: For any tech savy person wondering what specifically the bug was (or at least what I think it was), it was a missing buffer flush in the file output stream.

EDIT 2: If you're familiar with JSON formatting you can salvage most of the data by simply closing the braces and finishing the format. Won't fix the saving issue till 251 but at least you'll have a portion of your data intact.

**Comment by WesCook** [comment]
Good news, glad to hear you found the issue.

Is the bugfix being applied to both BQ2 and BQ3 branches, or just the latter?  Homestead is still running BQ2 at this time, but I'll definitely apply the fix if I can.

**Comment by Funwayguy** [comment]
I don't do support for BQ2 anymore. There have been too many changes and there are many more coming. Even if I did accept a PR to fix it in BQ2, this bug would probably be the least of your issues in those versions.

**Comment by WesCook** [comment]
Gotchya, no problem.  When I published the pack BQ3 was still in early alpha stages so it wasn't ready yet.  Don't think there's been an upgrade path so I've stuck with 2.

**Comment by Funwayguy** [comment]
BQ3 natively loads and converts BQ2 files (only in 1.12.2 though. I stopped working on the 1.10.2 version). Coming in build 251 it will also auto-backup every update just in case something goes horribly wrong (like with 248).

**Comment by WesCook** [comment]
It's a 1.10 pack unfortunately.  But I'll keep this in mind for the future, thanks!

**Comment by Mijithemidge** [comment]
I am having this problem myself. I made a modpack by myself, for myself, approx. 80 mods. However, the quest book is blank. I am using 1.12.2 and the latest version that was released just a few days ago, and have the mod that gives you an actual quest book instead of a keybind. I have no idea why the book would be blank as I just started this modpack yesterday and got the book today. I also have the standard expansion. The menu is fine, but there is nothing under quests. Hopefully this can be fixed.
