### ISSUE TITLE
[1.12.2] [BQ3] When opening the quests with the ` key, the chapter list has a scrollbar and the titles don't fit. When opening with the item from BQ Triggerer, it doesn't.

### ISSUE THREAD

**Issue by aaronhowser1** [Funwayguy/BetterQuesting#313]
[This](https://i.imgur.com/h7RwsKK.png) is what it looks like when I open with the BQ Triggerer, and is what it should look like I think. [This](https://i.imgur.com/7oatHue.png) is what it looks like when opening with the key, and looks bugged. This is using BetterQuesting-3.5.241 and BetterQuestingTriggerer-0.9C.

**Comment by Funwayguy** [comment]
That would be because BQ Triggerer is opening the old BQ2 legacy GUI I only _just_ replaced with a BQ3 version. The newer GUI has slightly smaller buttons and always shows the scrollbar now (there are a few technical reasons for this). It isn't a bug but a slight design change to dedicate more space to the quest line region. I've even removed the "Quest Lines" title at the top. I'll look into adjusting the buttons to wrap long titles into bigger buttons where necessary but the margins probably aren't going to change much for now.
