### ISSUE TITLE
GUI Elements Randomly Recoloring Pink and White

### ISSUE THREAD

**Issue by Boolyman** [Funwayguy/BetterQuesting#317]
Can you tell me what could cause certain aspects of the quest markers to be pink and white instead of the theme default?  I figured maybe a color code got mixxed up somewhere.  I can't identify it.  My defaultquest.json is attached. 
![2018-03-08 21_05_38-greenshot](https://user-images.githubusercontent.com/24765883/37191545-350071fa-2315-11e8-9130-ae67dd8b8ff3.png)

[defaultquestsjson.txt](https://github.com/Funwayguy/BetterQuesting/files/1795708/defaultquestsjson.txt)

**Comment by Funwayguy** [comment]
This likely has to do with one of the entity statue renderers leaking into the GUI due to OpenGL transparency not being reset after drawing. Considering this designer GUI is part of the old BQ2 code due to be replaced and it isn't a critical bug, I won't be fixing it right now. If it still does this in the newer BQ3 GUIs I'll look into it further
