### ISSUE TITLE
Client Crash - java.lang.NullPointerException: Updating screen events 	at betterquesting.client.gui2.CanvasQuestLine.isQuestShown(CanvasQuestLine.java:225)

### ISSUE THREAD

**Issue by ProsperCraft** [Funwayguy/BetterQuesting#322]
https://gist.github.com/ProsperCraft/86a82d19199ff16bcf9f74c3e2adce62

**Comment by MasterSloth1** [comment]
same problem here
https://gist.github.com/MasterSloth1/935be903a499dc7549be920365d23ed5

**Comment by Funwayguy** [comment]
I take two days off modding and everything crashes because of course it does. I'll get a fix out tomorrow for this. I need to move some in-dev code aside first.

From what I can tell this is being caused by a quest line with non-existent quest IDs... I don't even know how but I suspect some stupid BQ2 legacy code is contributing to the mess that is the database state.

I can't seem to recreate this on my own. How did you two do it?

**Comment by ProsperCraft** [comment]
I have several people editing the questbook, so it would be hard to provide steps to reproduce.

It have been possible the server was killed while someone was editing a quest(*whistles innocently*)

**Comment by Funwayguy** [comment]
Great... was testing my initial fix and it didn't entirely work. Doesn't crash anymore but it still doesn't update the quest line properly when multiple editors are messing with it. Why do you do this to me :sob: 

Got a better fix in the works for today's build though so not all is lost.

EDIT: New build uploaded. Should hopefully fix all of this up

**Comment by TheSnowyChickens** [comment]
Hello,

this crash is back.
https://paste.dimdev.org/esolemudez.mccrash

(I pressed the button for the retrieve detection task)
