### ISSUE TITLE
[Suggestion] UI Elements

### ISSUE THREAD

**Issue by Elvarion** [Funwayguy/BetterQuesting#323]
- Change color on Questline if all quests are completed.
- Change color on Questline if quest is completed and reward is claimable.

(Questline = The Tabs on the Left side)

If a hidden quest is still in a questline and not unlocked the Questline should still be marked as completed.
This way you can hide quests if so desired and people will still think the whole line is completed.

**Comment by Funwayguy** [comment]
I'm not really changing the design too much at the moment. I'm currently just trying to focus on porting the existing UIs from BQ2 to BQ3 code. In terms of the first two suggestions, when I do redesign things I won't be using nearly as many colours due to recent concerns regarding colour blind users. I'm also not sure that marking an entire quest line with their status is entirely necessary however I will consider adding a simple notification icon to say that there is something that needs attention such as an unclaimed reward or a incomplete (but visible) quest.
