### ISSUE TITLE
LuckPerms for editing quest in the server.

### ISSUE THREAD

**Issue by ThePlagueDoctor** [Funwayguy/BetterQuesting#330]
So I'm working with my server owner at the moment and we have no idea how to allow me to edit the quests while on server. I'm attempting to find this out to make things easier as currently the quests file is just being imported to the server from single player worlds when we update it.

**Comment by Funwayguy** [comment]
Only OPs have permission to edit the server and this permission cannot be lowered. This is because particular quest rewards can run commands as the server console and therefore bypass any permissions anyone would otherwise have. This includes, but is not imited to: opping/deopping any user including the server owner, shutting down the server, giving users access to admin commands by proxy without requiring OP status, and creating hidden macros to cheat or exploit.

EDIT: If you _are_ already OP then you can toggle edit mode using `/bq_admin edit`
