### ISSUE TITLE
BQ General Localisation

### ISSUE THREAD

**Issue by bashduude** [Funwayguy/BetterQuesting#334]
How do i make localisation with .lang files?
Can i get general example for two languages?
Iv'e read this thread(https://github.com/Funwayguy/BetterQuesting/wiki/Localisation).
Just need a bit more.

**Comment by EverNife** [comment]
https://github.com/Funwayguy/BetterQuesting/blob/1.12/src/main/resources/assets/betterquesting/lang/en_US.lang

**Comment by Funwayguy** [comment]
The reason I didn't really go into detail about lang files is because it's actually just a standard Minecraft feature in resource packs which you can Google search. If you supply a valid lang key as the quest name/description BetterQuesting will automatically use the current language translation for it. There are no restrictions on what the language key has to be (don't choose something confusing or vague though like "quest.title") or how many.

The idea is so that pack developers (or fan translators) can update themes and localisations in their packs just by swapping out the resource packs rather than manually editing all the quests again or installing/removing mods.

**Comment by hron84** [comment]
@Funwayguy actually, you should elaborate a bit more this part

> These files can alternatively be stored in Better Questing's resource directory for better bundling in packs published on launchers.

Also, some examples could help. Do we need to wrap the language keys specially? Do we need special structure for the resources? How resource files should be organized? Based on the betterquesting as a mod ID or somehow we should provide a specific resource ID? Some questions arise about this topic.

Please add more documentation about the localisation, because even if you think something is obvious for you as a mod developer, not neccessarily obvious or logical for us, translators who are not having deep knowledge about modding.
