### ISSUE TITLE
[Suggestion] Notifications For New Unlocked Quests

### ISSUE THREAD

**Issue by TheLimePixel** [Funwayguy/BetterQuesting#360]
In my pack I have 40 quest pages and after unlocking certain stages, new quests show up on some already unlocked pages. A bit of an issue is that players may not realize they have new quests on said pages. My suggestion is having some sort of notification, such as an exclamation mark or the number of unlocked quests appear next to the name of the quest page so they know there's something new there.

**Comment by Funwayguy** [comment]
Was already planning on doing something like this eventually but as like most of the UI changes that have been requested or I'm planning, it requires the rest of the GUIs to be replaced so I can roll out the full capabilities of the new themes otherwise the legacy screens could break down. I know that sounds like a bit of a ways off, and it is, but I really can't do a lot of major UI changes till then.
