### ISSUE TITLE
No Content in the Rewards and Tasks menus

### ISSUE THREAD

**Issue by CmdrNorthpaw** [Funwayguy/BetterQuesting#372]
I've been trying to create a modpack that runs mods that are compatible with Minecraft 1.12. I decided to use Better Questing to augment the experience, but there's a problem. I've discovered a bug where the Edit Taks and Edit Rewards menu contains absolutely nothing, as shown in these screenshots:
![screen shot 2018-05-02 at 16 15 45](https://user-images.githubusercontent.com/30018896/39529480-1608906a-4e27-11e8-9b17-899c245d0b25.png)
![screen shot 2018-05-02 at 16 15 33](https://user-images.githubusercontent.com/30018896/39529489-1c236b32-4e27-11e8-83de-3f072302a73b.png)
I've tried relogging, restarting the game, redownloading the mod and even rolling back to a previous version! Please help!

**Comment by Funwayguy** [comment]
Not a bug. The base mod doesn't contain any tasks or rewards. You need the Standard Expansion for those.

**Comment by TheLimePixel** [comment]
What's the point in having them separate though?

**Comment by Funwayguy** [comment]
They are made separate so that they are easier to maintain. The base mod is already a huge pile of systems I'd rather not have to rebuild every time I need to change something with a task or reward unrelated to the base mod. Not only does the base mod also act as the API to other expansions, the standard expansion is an example for developers to use as reference developing their own.
