### ISSUE TITLE
Add an option so that a single task can be automatically partially comleted

### ISSUE THREAD

**Issue by aaronhowser1** [Funwayguy/BetterQuesting#373]
As is, you need to have everything in the task for it to be detected. For instance, [this quest](https://i.imgur.com/q1id46B.jpg) (taken from [this video](https://www.youtube.com/watch?v=jFITE422aNM) at 6:30) requires you have all that at once to automatically detect. You could click the detect button to detect what you have and that works, but most players won't. This quest requires getting the Tier 1 Void Resource Miner, but if they can they'll upgrade directly to the Tier 2 one, leaving this quest uncompleted. You still have to have everything in the Tier 1 quest, but the player doesn't have them all in their inventory at the same time.

This also leaves the problem that the player could have the entire tier 2 miner created and in their inventory which would complete the T2 miner quest, but it isn't unlocked because the T1 quest wasn't completed. It would also be very useful if there was a togglable option to allow quests to be completed out of order.

**Comment by Funwayguy** [comment]
Automatic detection does work (when not in edit mode) but for retrieval quests it ticks only once every few seconds to prevent the server keeling over from checking everyone's inventory every tick for every item task. If players doesn't have it within their inventory long enough for one of these update passes then it will miss the check. The task type also has an option called `groupDetect` that can be turned off so that teach item is detected individually instead of all at once.

Out-of-order questing is already possible with a setting called `lockedProgression` but as long as it has the hard requirement of the tier 1 quest as a pre-requisite it won't complete.

**Comment by aaronhowser1** [comment]
All my quests have [groupDetect off](https://i.imgur.com/ofUAPw9.png) but they don't automatically detect the separate parts of the task (like autodetecting the Miner Controller while that's the only thing in the inventory) no matter how long I sit there (while using 252). 

Although after updating to 254 from 252, nothing is detecting at all with edit mode off. [This should be detecting right?](https://i.imgur.com/6QQkdj8.png) I have 64 Oak Logs in my hotbar and I waited for like 2 minutes to make sure I didn't just have to wait. I could complete the quest with the Detect button though.

**Comment by Funwayguy** [comment]
Hm... seems the experimental change broke more than I expected.

**Comment by Funwayguy** [comment]
Build 225/256 should have this fixed. Revised the experimental changes and tested to make sure everything was mostly in order.
