### ISSUE TITLE
No text in new Description editor

### ISSUE THREAD

**Issue by Insane96** [Funwayguy/BetterQuesting#378]
Sometimes when you write in the text editor the text completely disappears.
![immagine](https://user-images.githubusercontent.com/7185104/39771221-a8a1aa28-52f1-11e8-8951-4345d65a651e.png)

**Comment by Funwayguy** [comment]
Which version of Better Questing are you using? are there any errors in the console logs?

**Comment by Insane96** [comment]
Minecraft 1.12.2
Forge 14.23.3.2668
Better Questing 3.5.256

The log was spammed with this
`[18:56:25] [main/ERROR] [betterquesting]: Line count mismatch (24 != 23) while drawing formatted text!`

Quests File: https://pastebin.com/tkEB0pm1
Quest at line 8232

**Comment by Funwayguy** [comment]
Just confirming I've been able to recreate it and it's not unique to the editor either it seems. I have found the issue and fixed it in dev but I'm not sure if I can put a fixed build right now. The database code is a bit of a hot mess at the moment due to it being in mid rewrite. I'll see what I can do about tidying up the work-in-progress code to make an interim build

**Comment by Insane96** [comment]
Well, I'll revert back to 3.5.250 when there was no problem until a fix is out
