### ISSUE TITLE
auto detection of complete quests no longer works

### ISSUE THREAD

**Issue by mvdhoning** [Funwayguy/BetterQuesting#388]
I had a starter quests that rewards the player with a book on breaking a log from a tree without accessing the quests first.
Now i have to go to the quest and click detect and next click collect.
This worked before updating the better questing mod.

Try this to see the bug in action: https://minecraft.curseforge.com/projects/medieval-life (or to put better  the lack of action ;-) )

**Comment by Funwayguy** [comment]
Before I go download an entire modpack just to test this, can you double check you just haven't left edit mode on in the default quest file?

**Comment by mvdhoning** [comment]
i double checked that (only the version i am sure on is not yet approved 2.6.8)
also managed to reproduce it by making a new modpack with only better questing mods. so no need to download the modpack.

**Comment by Funwayguy** [comment]
I was thinking over how this could be happening and it just occurred to me that it's because I made only tasks that need to check/scan something constantly (like items in your inventory or location tasks) able to fire auto completion checks because of unnecessary extra load the others were causing and preparation for migrating to event based completion checks. Guess there were a few edge cases that were missed and can't auto-complete anymore. Unfortunately I'm busy dealing with more pressing parts of code at the moment but I'll see what I can do later down the line.

**Comment by Funwayguy** [comment]
This should hopefully be fixed in the next build (258). Had to make a few edits to how the quest cache works to account for this. To keep the load somewhat under control, it only updates these particular quests once every 3 seconds. Unfortunately I can't do instant auto-completion until the whole system has been replaced with a proper event based updating so this will have to do for now.

**Comment by mvdhoning** [comment]
updated to 258, but it does not seem to be fixed
