### ISSUE TITLE
Questbook tabs can't be moved anymore

### ISSUE THREAD

**Issue by TheLimePixel** [Funwayguy/BetterQuesting#390]
When I joined my world after updating to the latest version, the quest tabs were all mixed up. The worst part is that it seems that the arrows for moving them simply don't work anymore.

**Comment by Funwayguy** [comment]
Found and fixed it for next build. This is only a minor visual bug so unless you've actually pressed the buttons try and move the quest lines around, they will revert to what their original sort order was when you update next. If you have moved them you'll just have to remember to move them back, no data is actually lost though.

**Comment by Darkmega18** [comment]
Ah, I got this too. but thankfully mine didn't jumble and it seems all my stuff from the latest version 2 that I updated to the latest 3 carried over just perfectly, which is great. Now I just need to move my tabs so my questlines are in order, but next version then.

**Comment by Funwayguy** [comment]
Good to hear everything migrated across without issue. Hate to have another 248 build on my hands (_eye twitches with PTSD_). I'm going to give it another day or so for bug reports to roll in and do some minor polishing of the new code before I post the build for this fix.

After that it's onto registry rewrites. Not as likely to cause mass corruption as this update but still significant enough to crash things.

**Comment by Darkmega18** [comment]
Yeah, I was putting it off for so long. but then I saw a direwolf20 video from just recent with them playing FTB continuum and they had 3 installed, so I figured, if they consider it stable enough for them, I'll give it a go also cause it'll probably be beneficial to transfer it over in the end provided it works, which it did. and ouch, whatever that build was, it must've broke pretty dang hard. D: 

Question. although it probably deserves it's own issue. The commands and running the commands "via player" is it possible to make the player getting reward to run commands that would otherwise only be useable by a player now? such as loading a schematic with worldedit and making it as if the player only with permissions runs the command and then after a very big warning in the next quest spawn said schematic which may be a structure with some special spawners in it to act as like spawning in a small Arena with an encounter in it? Or is that completely out? Cause I've been looking for a way for a survival based quest mod to spawn in a boss made using custom NPCs or something and not have people be asses and spawn them in grinders and cheese them out and shit. :V or like, for specific location based quests to spawn a structure of some kind using a command and such...

**Comment by Funwayguy** [comment]
I consider 3 much more stable than 2 ever could be, even in its unfinished state. Build 248 caused irreversible data loss and had to pulled from Curse. This is why they aren't marked as release builds. Even though they are more stable, things can go horribly wrong as I continue rewriting the internals. Newer builds have auto-backups now so if you did want to go back to 2 then you can find the old original files in those backup directories.

`viaPlayer` just means it runs as if the player typed it. When disabled it acts as the server console. In both cases it runs with maximum OP permissions. So yes, `viaPlayer` would likely work for structure summoning commands. You can also just run entity summon commands too.

**Comment by Darkmega18** [comment]
well dang, D: but yeah, since it transferred fine, I'll be sticking on it then once I save my next set of quests and make sure it's fine.

I ask about the viaPlayer thing cause it never worked with worldedit commands even so in 2, so I'll definitely have to try it again now that I've got 3. :o
