### ISSUE TITLE
[1.7.10] Still accepting PRs/license request?

### ISSUE THREAD

**Issue by richardhendricks** [Funwayguy/BetterQuesting#410]
Hello,
  We are using BQ for our giant Gregtech 1.7.10 modpack, and would like to do some changes to how your mod operates.  Can we get permission to modify your 1.7.10 code and release files just for our modpack use? I guess with 1.7.10 you probably are not accepting PRs anymore.

Changes
1. Fix for server lag caused by sending quest database to every player when updated.
2. Allow legacy file format to use PARTY_LOOT setting.
3. Change defaults for quests to Consume: False
4. Adjust scrolling so quests are shown left-justified by default in quest window.
5. Add message that GT:NH version is only for use with GT:NH modpack/remove update checking

We have over 1,500 quests, and your mod is key to controlling the player's progression. Thanks a bunch for your work.

**Comment by Funwayguy** [comment]
I don't usually allow PRs (new or old versions) because BetterQuesting is a very large amount of code that I'd rather not have people throw ideas into that could potentially break other people's packs or otherwise be useless to everyone but the requester.

You also need to keep in mind that the 1.7.10 version is already missing a ton of the internal fixes I made in BQ3 for 1.12.2 such as using NBT internally instead of having to convert JSON all the time, making the databases thread safe, upgrading GUIs to not be an absolute mess to manage, ongoing VR support and numerous other small upgrades.

But sure... if you want to take a shot at it I guess you can 'fork' the repo and make an attempt at doing what you want to it but I'm not going to help. Just be sure to mark the build as a custom version and unsupported so I don't get sent bug reports for it.

As a final word of warning, there's a reason I've started burning that old code to the ground. It's inflexible, unstable and tedious to work with. I hope you know what you're getting into.

**Comment by richardhendricks** [comment]
As a 1.7.10 modpack that's been in development 4+ years , we are stuck supporting what we support.  Most of our mods aren't available or aren't in the same state yet in newer minecraft releases, and converting a quest database of this size would be formidable. Maybe someday!

Thank you very much for your permission, we will be clear in the mod that it is ARR you, but that any and all support must come through us.

**Comment by Funwayguy** [comment]
The quest database itself would be dead easy to upgrade, the items and entities contained however is another matter. BQ3 1.12.2 can load BQ2 1.7.10 databases just fine and even backs it up for you in case it fails. I still test importing HQM modpacks from 1.7.10 just as a worse case scenario.

EDIT: Thanks for the Patreon by the way.

**Comment by richardhendricks** [comment]
Thanks, that's good to know. The texts to the quests is half the battle (GI JOE!) so we will definitely keep that in mind if/when we decide to migrate.  With 200+ mods, it might not happen any time soon, hence we have been forking more and more mods to manage ourselves.

**Comment by richardhendricks** [comment]
Just to be clear, the authorization also covers the BQ expansions? We would to change some of the quest task defaults (ie, consume to false) that we commonly forget when making new quests.  Thanks.

**Comment by Funwayguy** [comment]
There is a copy/paste function in the quest line designer. You could just make a set of template quests and copy those as necessary. Modifying a whole expansion just to change a few defaults seems a bit excessive.

**Comment by richardhendricks** [comment]
We'll look at that then.  What about the error messages for checking versions?  SE and RFE return error messages, and we would like to remove them.

https://media.discordapp.net/attachments/346762422754869248/461975405587333131/unknown.png?width=1231&height=693

**Comment by Funwayguy** [comment]
Going to close this now that there's a new backported version licensed under MIT. You'll need to update your expansions to be able to use it but once you do things should be much easier to modify and/or maintain.

**Comment by richardhendricks** [comment]
Thanks so much. Since there is no license file included in the 1.7.10 branch I will assume the LICENSE in 1.12 applies.

https://github.com/GTNewHorizons/NewHorizons/issues/4334

**Comment by Funwayguy** [comment]
Whoops, forgot about that in the backport. I'll copy those licenses across later today
