### ISSUE TITLE
The Party Page Is Still Broken

### ISSUE THREAD

**Issue by TheLimePixel** [Funwayguy/BetterQuesting#432]
Even after version 3.5.263, you still need to click the buttons and text boxes on the party screen a couple of times to get them working.

**Comment by Funwayguy** [comment]
I couldn't recreate this before and it turns out it's a side effect of quests refreshing the database for things like submission stations or repeatable quests resetting, something other GUIs are affected by too. I need to rework the underlying update event a bit to fully fix this but there are still old legacy GUIs using it. I'll see what I can do about it in the mean time.

**Comment by Funwayguy** [comment]
Pretty sure this has long since been fixed. Closing...
