### ISSUE TITLE
[Feature Request]Trigger Finger safeguard

### ISSUE THREAD

**Issue by remclave** [Funwayguy/BetterQuesting#450]
I suffer from Trigger Finger (even diagnosed by a doctor when I never mentioned it to him). In the course of editing in the Better Questing edit mode, I have experienced accidental mouse clicks. Other modes it is not an issue. While in delete mode, however, I have lost hours, and sometimes days, worth of work with an accidental click while moving the mouse cursor over to select another mode from the menu icons. 

Is it possible to add an "Undo Delete" button or possibly add an "Are you sure you want to delete?" option for (semi or otherwise) handicapped developers?

**Comment by Funwayguy** [comment]
Unfortunately I can't add an undo for particular actions due to the fact that multiple editors can be making changes to a single quest on a server at any given time and I'd effectively need to setup a git style tracking system on who's edited what and merge/split data when someone hits starts/stops editing or wants to undo something (not impossible but quite a huge rewrite on top of what I've already got).

What I can do is try and setup a sort of global roll back system where you can reload to a previous state should someone make a mistake. For example, hitting Ctrl+S to save the current state and then using Ctrl+Z to reload it if something went wrong (maybe support for multiple states?). The difference being that every player editor on a server shares these states and using it will undo everyone else's changes within that period too.

Would that be okay with you?

Note: I may not get to adding this immediately. Still have some other work to cover first but I'll add it to my todo list of things to get done.

**Comment by remclave** [comment]
I think it is best to leave well-enough as status quo. There are a lot of questbook devs who would potentially lose scads of progress and that would really piss off server owners. So I will endeavor to keep my fingers away from the mouse button when I'm moving the mouse to select a different icon. 

Thank you so much for your thoughtful reply.
