### ISSUE TITLE
[Server] 1.12 - A player in a party isn't having their quests synced with the others

### ISSUE THREAD

**Issue by TheFlash787** [Funwayguy/BetterQuesting#456]
Hey! So I'm running Better Questing in the Enigmatica 2: Expert Skyblock modpack however with a certain player, when they are added to a party that already has progress, they aren't seeing the progress in their quest book. 

They are still able to do quests and receive rewards but even if a member of their party completes a quest prior to this, the player still does not received the updated quests from the party.

Any help is appreciated, Thanks!

**Comment by Arudarin** [comment]
Related to #344?

**Comment by TheFlash787** [comment]
> 
> 
> Related to #344?

Very Possibly ^

**Comment by Funwayguy** [comment]
It might have to do with how I'm caching unlocked quests to reduce TPS impacts. I'm eventually going to be removing progress inheritance altogether in BQ (merging and splitting progress has always been a mess) so I'm not sure if fixing this would be time well spent. If it's a minor fix that can be done in the short term then sure, otherwise I'll probably just leave it for now before removing it outright.

NOTE: Parties will still be able to complete quests together, you just won't be able to slingshot users forward. The general idea is for it to function more like MMO questing so server operators don't have to worry about users exploiting progress inheritance. It's also much faster to handle data when I don't have to pull and merge the entire user's party data to check completion or unlock statuses.

**Comment by Arudarin** [comment]
Hm. Is there a way to copy-paste user quests?

**Comment by Arudarin** [comment]
@Funwayguy

**Comment by Funwayguy** [comment]
What do you mean exactly by user quests? If you mean just progression, not unless you do it from within the JSON file.

**Comment by Arudarin** [comment]
I see. Would it be possible to do a sed command, e.g. sed -i 's/*Member1's UUID*/*Member1 and Member2's UUID*/g' *json file* ? @TheFlash787

**Comment by Arudarin** [comment]
Also, can you give us some details on the JSON file's format @Funwayguy ?

**Comment by TheFlash787** [comment]
We understand this issue will not have an easy fix due to the 'slingshotting' being removed entirely. Thank you for telling us this and I will close the issue. Thank you
