### ISSUE TITLE
Updating quests fails with "ID cannot be negative"

### ISSUE THREAD

**Issue by thehobojoe** [Funwayguy/BetterQuesting#489]
When updating the defaults with `bq_admin default load` via a command quest reward, a non-fatal crash report is generated.

[crash-2018-11-17_01.48.29-client.txt](https://github.com/Funwayguy/BetterQuesting/files/2591592/crash-2018-11-17_01.48.29-client.txt)

When updating via typing the command directly, this crash does not occur. The DefaultQuests.json does not have any negative quest ID's, as you can see here.

DefaultQuests.json: https://pastebin.com/zwW6Sp1r

From my limited testing this does not appear fatal and the quests seem to update correctly, however it's quite confusing to users with the visible error popup show in the top-right, making it seem as if the process failed.

Using BQ 3.5.275

**Comment by Funwayguy** [comment]
This isn't a necessarily a bug and isn't something you should be doing. This is a concurrency issue where the quest database is editing itself from within itself mid tick on the server. Just because the command reward _can_ run any command doesn't mean there aren't ones you really shouldn't be trying to do in this context. I may add support for this later but right now there are better ways to update the database that doesn't involve concurrency issues and potential corruption.

There are new tags in that you can edit in the quest properties (same place the splash is set) that can version the database and give users a button prompt to update themselves safely.
