### ISSUE TITLE
[1.12][request] config option to disable parties

### ISSUE THREAD

**Issue by mensreaMC** [Funwayguy/BetterQuesting#498]
Like the title says, just a simple option to disable parties.

**Comment by superon** [comment]
i second this, didn't know it wasn't an option that would even be an issue until i started completing quests that i'd not even had access to after someone created a party.  i didn't even join the party, so this not being an option does seem a bit broken if the mechanic is intended :/ (1.7.10 btw)

**Comment by Funwayguy** [comment]
I'll see about adding an option for disabling parties for now but I'm going to be rewriting how they work in future anyway, first by removing any kind of progress "sling-shot" provided by joining late game parties.

@superon I'm not currently doing support for any version besides the new 3.5.xxx builds in 1.12.2. Major changes in code have been made since previous versions and I can't backport a lot of it right now.

**Comment by superon** [comment]
thank you for the response, i know you're a busy guy too so have to ask if it's ok for me to ask others to create a mod to disable the party option? ... although i don't know if this is even possible i feel it necessary to continue with the development of my modpack which has now been ongoing for around 3 years and recently returned to beta status :/

**Comment by Funwayguy** [comment]
Closing this as the option was added a few versions back

**Comment by Omegapsychosis** [comment]
Is this a config option you added? I am using Better Questing 3.5.300 and am not seeing how to disable parties anywhere (I may be blind)

**Comment by Funwayguy** [comment]
Where you'd normally set the spash screen or quest version is where you'll find the setting.
