### ISSUE TITLE
[Feature] Hold Backspace to Delete

### ISSUE THREAD

**Issue by ghost** [Funwayguy/BetterQuesting#50]
I am currently working with this mod to create a modpack, and I've noticed that deleting things (especially the default texts) is really tedious because I can't hold backspace to continue deleting. I have to press it for every character. I am just wondering if this is a feature already in the works or something and when you think it will be possible. Also, it would be nice to click and drag to highlight sections of text and delete them. I know that's a lot harder and it's not really necessary, just an idea.

**Comment by ghost** [comment]
on further inspection, you can hold backspace to delete when in the rich text editor, but it would also be useful to have in things that don't have  that option, like the title and such

**Comment by Funwayguy** [comment]
The inability to hold backspace was an oversight on my part which I will get fixed up in a later update. The text selection is a little more tricky however due to all the dynamic rescaling of the UIs. It's very difficult to keep track of where exactly the letters are being drawn so trying to do a drag select is probably not going to happen any time soon, sorry.

PS: In the mean time if you need to delete the default text really quickly, Ctrl + A should still work for selecting everything

**Comment by ghost** [comment]
okay cool that will work! I knew the click and drag was a little out there. I have been trying to make quests but the navigation of the system is really confusing.

**Comment by Funwayguy** [comment]
Just a status update on this, in my dev build I have all questing UIs now support holding of keys including backspace.

**Comment by ghost** [comment]
Hooray
