### ISSUE TITLE
Java Rendering Crash

### ISSUE THREAD

**Issue by HogPilot01** [Funwayguy/BetterQuesting#501]
The game crashed while I was using designer and trying to open the icon item list.

Report: 

https://pastebin.com/y7EZUZc9

Version of Better Questing: 3.5.277

Standard Expansion: 3.4.145

**Comment by Funwayguy** [comment]
Seems to have something to do with Creative Plus Wands. I'll take a look at their code later and see if I can identify what's causing it.

**Comment by HogPilot01** [comment]
I removed Creative Plus and that fixed it. Thanks.

**Comment by Funwayguy** [comment]
Seems this particular crash is caused by tooltips on Wands not checking if the active material even exists before trying to use it. Unfortunately there appears to be quite a few missing checks in other palaces where you can outright crash the client or server just by giving someone a wand with an invalid tag.

![image](https://user-images.githubusercontent.com/6048596/48991788-45906900-f180-11e8-8369-5600c49d48de.png)

Feel free to report this to their issue tracker (if they have one) and link back to here.

EDIT: Here's a fun thing to test. Set the wand material to a modded block and then uninstall the mod the block belongs to. This may very well brick a client from logging into a world until the wand is removed or the mod is reinstalled.

EDIT2: For even more fun, if you can manage to summon a wand with a block ID that is present in a mod installed client side but not on the server or any other player's client, you are potentially immune to the crash and can just toss players the item to knock them off line. Better yet, attempt to use it and take the entire server down without taking your client with it.
