### ISSUE TITLE
[1.7.10]soft client crash on detect rf quest

### ISSUE THREAD

**Issue by skull1** [Funwayguy/BetterQuesting#525]
forge: 10.13.4.1614
BetterQuesting: 2.0.233
StandardExpansion: 2.0.121
RfExpansion: 2.0.25
i tried make a simple quest( https://puu.sh/Cuwoa/6286b0793d.png ) for detect rf and reward, but when i click on detect/submit the client soft crash(im on single player), if i use the rf station, on the quest the progress of rf seems locked(i also had a hard crash trying to open the quest while the rf station was accumulating rf but couldnt replicate it).
i tried the same with an old version of bq and rfexp, and it worked good, but im planning of make a quest that requires 1billion+ of rf, which on old version his limited to 1b...

https://pastebin.com/L2cUF1uN launcher log with some errors before cause the soft crash

**Comment by Funwayguy** [comment]
Unfortunately I'm not currently doing support for any other versions besides the 1.12.2 branch until all that can be back ported safely. 3.x.x code is considerably different from anything previously written.

At a glance that error is a strange one. Looks like something with the player IDs is messed up. Looking around the code I can see that there is a bug with the RF task in that it uses an unsafe method of tracking progress (which has long since been deprecated in BQ). Seems you've found one such edge case where this fails badly.

I don't have any short term solutions to help on such an old version. I'm not a fan of working with the old code considering how temperamental it can be. Is it absolutely critical to have this version fixed now?

**Comment by skull1** [comment]
it's not that urgent, i will use the old one,make the quest less difficult and arrange it somehow, just sometime throw an eye on that 1.7.10 version, the last update was on 2017,but i understand you have higher priorities with the 1.12.2 branch.

**Comment by Funwayguy** [comment]
As much as people are probably passing it off as an April Fools joke, the new builds for 1.7.10 I've uploaded for Better Questing, Standard Expansion and RF Expansion are legitimate and should resolve this issue for you. It's completely rewritten too so I can do future bug fixes for it if you run into any more issues.
