### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by Spontini** [Funwayguy/BetterQuesting#541]
Hello, i'm running a server and this is how it is all time.. the only thing rapes my server is Standart Expansions all time, do you guys have any idea about how to fix it?
https://imgur.com/a/sBXOkRN
Logs: https://paste.feed-the-beast.com/view/3cafa58a

**Comment by Spontini** [comment]
https://sparkprofiler.github.io/#4PW3qJzzq7

**Comment by Funwayguy** [comment]
I can sort of fix this but it's not directly Standard Expansion's fault and Lag Goggles is really bad about blaming the wrong mods because it doesn't understand how cross mod interactions affect things.

In this case the retrieval tasks are waiting on other mods to deal with their item stack capabilities when doing item lookups and comparisons on the player's inventory. If these capabilities are particularly slow then Lag Goggles incorrectly blames BQ even though it's completely outside of its control. This is why I'd rather people do proper profiling reports that tell the full story of what BQ is waiting on and from who (so thanks heaps for including that).

In the profile report you provided it appears Nuclear Craft is taking quite some time with its radiation capabilities (not the first time I've seen this mod show up). Thankfully I have contact with the dev so I'll see about getting them to fix it on their end. Astral Sorcery is also making a small dent with amulets but is negligible compared to Nuclear Craft.

PS: Your report also shows that your server is having considerable latency issues elsewhere, particularly with mob spawning attempts (takes up 24% of processing alone) and Exnihlo Creatio barrels spamming relighting checks for some reason (5% every tick).
