### ISSUE TITLE
[SUGGESTION] Option to Center Quests On Page.

### ISSUE THREAD

**Issue by remclave** [Funwayguy/BetterQuesting#547]
When I create quests I center all activity. When I exit then re-enter the quest line for editing, everything in the main field is hugging the right side of the GUI. When viewing the same quest line under conditions of play, the main field is hugging the left side of the GUI. Is there any way to CENTER on the "isMain" icon for both and/or have them open in the last (player/design) position in the GUI?

Player GUI:
![2019-02-11_13 02 48](https://user-images.githubusercontent.com/31051239/52586644-9fa6df00-2dfd-11e9-898e-d4b403c15513.png)

Designer GUI:
![2019-02-11_13 03 08](https://user-images.githubusercontent.com/31051239/52586658-a897b080-2dfd-11e9-8a02-c20ee72f978c.png)

**Comment by Funwayguy** [comment]
I've fixed centring the visible portion of the quest line in 292 but it currently isn't dependent on `isMain` particularly because that visual option is getting removed in favour of just setting the icon frame to whatever texture you want.

I'm thinking of allowing the view to snap to active quests but that's not currently planned for the next few builds at least because there's a bunch of other things the snapping will have to account for that isn't currently implemented.

**Comment by remclave** [comment]
I'm a bit slow on catching up with my open issues... sorry. 

Thank you for your reply Funwayguy. I look forward to seeing the changes in the future. I will enjoy the mod as-is in the meantime.
