### ISSUE TITLE
Crash on certain mobs in hunt tasks

### ISSUE THREAD

**Issue by Yakaita** [Funwayguy/BetterQuesting#548]
this is the crash report for it. it seems to crash only on some mobs, this mob was the fluid moo from the mini moos mod. the only thing I could think of is maybe it's crashing on mobs with a ton of nbt. the mini moo mod has one entity changes to be a random liquid in the game.

[crash-2019-02-12_17.48.19-client.txt](https://github.com/Funwayguy/BetterQuesting/files/2858008/crash-2019-02-12_17.48.19-client.txt)

**Comment by Funwayguy** [comment]
That specific crash report should probably be reported to MiniMoos. Their entities seem to have no fallback if a fluid cannot be loaded, either from a missing mod or intentionally omitted.

This line can return null fluid types:
https://github.com/RicardoTheCoder/MiniMoos/blob/1.12.2/src/main/java/com/ricardothecoder/minimoos/entities/EntityFluidMoo.java#L121

While this line doesn't check if the above has returned null when saving to NBT data:
https://github.com/RicardoTheCoder/MiniMoos/blob/1.12.2/src/main/java/com/ricardothecoder/minimoos/entities/EntityFluidMoo.java#L581

This is what is resulting in your crash when a fluid is not available or is marked as "None". Unfortunately judging by the MiniMoos CurseForge page, seems chances of getting things updated and fixed on their end is pretty slim.

I might add in a fallback in a future update to handle broken entities like this and prevent users from attempting to use them until fixed by their respective devs.

**Comment by Yakaita** [comment]
this has also happened with other mobs. ill add the other reports as well so you can see those and see if it is the same error or not

this crash was happening at a different part of the book. I got 5 crashes like this
[crash-2019-02-12_18.42.09-client.txt](https://github.com/Funwayguy/BetterQuesting/files/2858252/crash-2019-02-12_18.42.09-client.txt)

this was the first time the crash happened. this is with a different mod instead of mini moos. there are 5 of these that aren't mini moos mobs
[crash-2019-01-31_15.15.42-client.txt](https://github.com/Funwayguy/BetterQuesting/files/2858254/crash-2019-01-31_15.15.42-client.txt)

**Comment by Funwayguy** [comment]
That first one is another busted check in MiniMoos however the code that broke isn't on GitHub (had to decompile the last release version to find it). Again, not likely to get fixed unless another dev gets permission to start maintaining it.

The second is also not a BQ bug (doesn't even involve BQ's code) but something up with DrZark's GUI API in Mo' Creatures. You'll have to report it to them to get that fixed.

I'm just going to close this issue here seeing as these are all mostly unrelated to BQ itself.
