### ISSUE TITLE
Add Permission System, based on Forges PermissionAPI

### ISSUE THREAD

**Issue by Peda1996** [Funwayguy/BetterQuesting#550]
On my Server, i want to create a certain amount of players, who can then edit quests. According to the sponge documentation, this could be possible:

https://docs.spongepowered.org/stable/en/plugin/permissions.html#for-forge-mods

Would be cool if this could be added.

Reguards

**Comment by Funwayguy** [comment]
Better Questing already makes use of OP permission levels however it will only ever be accessible to the highest level. This is because command rewards have incredible power and any malicious editor could setup hidden quests as macros to force the server to OP/DEOP anyone and everyone repeatedly plus automate any other destructive commands at will. For these reasons, the permission will not be lowered.

**Comment by Peda1996** [comment]
Thanks, never thought of it this way.
