### ISSUE TITLE
Parties Not Syncing

### ISSUE THREAD

**Issue by NielsPilgaard** [Funwayguy/BetterQuesting#553]
Hey o/

I'm getting reports that quest progress for players in teams is not shared, for some.
I'm unsure what additional info to supply, but I'd be happy to (try to) dig up whatever you need.
Original issue: https://github.com/NillerMedDild/Enigmatica2/issues/343#issuecomment-464884889

### Versions
- BetterQuesting-3.5.291
- StandardExpansion-3.4.151

**Comment by Funwayguy** [comment]
Some of this behaviour might be intentional.
- Shared loot is a quest side config and not party enforced to better support adventure packs and allows players to leave their parties without losing access to the shared item (especially if it's a key quest item).
- Party progress sharing is getting changed to disallow "sling-shotting" progress of players joining a party. This means that existing party members will be able to assist new members but they won't inherit progression without an OP forcing such a sync.

Something does appear to be broken here but I'm going to need more information about it to test.

**Comment by NielsPilgaard** [comment]
Neither of those intentional behaviours fit the issue: They both started from scratch with no quests completed, and it's the completation of quest tasks that's not shared, AFAIK anyway - We'll see what OP says :)

**Comment by Yakaita** [comment]
> Neither of those intentional behaviours fit the issue: They both started from scratch with no quests completed, and it's the completation of quest tasks that's not shared, AFAIK anyway - We'll see what OP says :)

he is op

**Comment by NielsPilgaard** [comment]
OP as in original poster.

**Comment by Yakaita** [comment]
then are you not op?

**Comment by NielsPilgaard** [comment]
I linked to an original issue in the description of this issue, I was refering to the poster of that issue. Either way, it looks like the issue has been resolved, I'll reopen if it starts acting up again - Thanks :)
