### ISSUE TITLE
[1.7.10]Server Side Crash

### ISSUE THREAD

**Issue by NialMontana** [Funwayguy/BetterQuesting#555]
So I've been recently working on a private modpack for use on a family server however upon testing it server side (I've been working client side only before now) I get this crash: https://pastebin.com/cjvcSAWg

The crash log references a missing class file that I have personally check does exist in the mod jar and have made sure all the addons and base mod are at the latest release (being on 1.7 this is fairly hard not to do). The modpack works absolutely fine client side and only crashes upon starting it on the server.

**Comment by Funwayguy** [comment]
The error has more to do with client side only code being loaded on the server, not necessarily that the file is missing. Unfortunately I'm not currently doing support for any versions besides the latest 1.12.2 because almost everything has been internally rewritten since then fixing possibly hundreds of issues that versions like this have. I do know there are working 1.7.10 versions that will launch on a server but I can't remember which they are (download counts might be a good indicator to figuring out which).
