### ISSUE TITLE
[suggestion]biome and structure quests

### ISSUE THREAD

**Issue by stefanovich123** [Funwayguy/BetterQuesting#574]
I want something that will check biomes and structures quests like if you enter a biome or structure you completed a quest or if you kill an enemy in this biome.
If you plan to do this then thank you because it is a feature that will be very useful.
(this issue is closed because it makes more sense that i posted it on betterquesting standard expansion

**Comment by Funwayguy** [comment]
Can you please stop opening and closing the issue. I've been asked several times about it already (even today by a streamer over this exact thing). I will get around to supporting it eventually but I don't have an ETA on it.

PS: I don't really care which one people post it on any more because nobody would follow the rule anyway
