### ISSUE TITLE
Crash when selecting Thermal Dynamic's "Transport" as Entity to Meet (ie, I did a dumb thing)

### ISSUE THREAD

**Issue by katubug** [Funwayguy/BetterQuesting#588]
First off, I know I shouldn't have chosen this and tried to commit the change. I wanted to see what a "Transport" was, and accidentally clicked "Done" without selecting the mob I ACTUALLY wanted to target.

But, it prompted me to send you a crash report, so here it is: https://paste.dimdev.org/ucafaneqav.mccrash

**Comment by Funwayguy** [comment]
I'll try and add in some fail safes to stop the use of technical entities but that's pretty difficult because things like minecarts aren't living things but are still valid choices. In the mean time, if you know what the quest is you can erase it from the JSON database file manually (or just delete the quest before opening it)

**Comment by katubug** [comment]
I did delete the quest before opening it, and all was well. Honestly, I have to commend you for how stable the mod is. I really appreciate all the work you've clearly put into this.

**Comment by Funwayguy** [comment]
Glad that's resolved without any permanent data loss. I've included a potential means of handling these entities within the next build.

As stable as BQ is, there's still plenty of room for improvement, especially on the appearance and networking side of things. Hoping to whip up some new themes and better accommodate colour blind users (a big problem I didn't account for).

**Comment by Funwayguy** [comment]
Build 3.5.299 on Curse has a error handling for this now.
