### ISSUE TITLE
Enhacnement: JEI integration for task items. In 1.12.2

### ISSUE THREAD

**Issue by SirAron111** [Funwayguy/BetterQuesting#594]
Enhacnement: JEI integration for task items. in 1.12.2

Would it be possible to make JEI with the recipe pop up if you click on the item required for a crafting or retrieval task? Would save a lot of time! I have seen many player try it and be disappointed it didn’t work.

**Comment by Azibu** [comment]
yes that would be much better

**Comment by StoneLegion** [comment]
Almost 2 years since this was asked. I hope it comes soon. It's sad but people now trying to make ftb quests converter just to have the quality of life features.

Original Request: 
https://github.com/Funwayguy/BetterQuesting/issues/430 

Oh older one in the comments of this one :)
https://github.com/Funwayguy/BetterQuesting/issues/61

Thanks.

**Comment by Funwayguy** [comment]
Closing now that this is supported in SE
