### ISSUE TITLE
Could you please explain the show option for quest lines?

### ISSUE THREAD

**Issue by Winddbourne** [Funwayguy/BetterQuesting#597]
I'm going through the options:

Normal
Completed
Chain
Always
Hidden
unlocked

But I have no idea what they mean or how to use them.  The names are slightly confusing.

Normal seems to always show . . . but since I see "always" I assume there is a way to hide a normal quest line. 

Completed . . . I'd assume this only shows quests that are completed? But if that is the case how would the player know the quest exists? Or does it show the entire line when ANY quest is completed so I could have a quest in two places and when it is finished elsewhere that unlocks this quest line? 

But if that is the case what is "unlocked" for? And how do I use unlocked?

Hidden? Does that mean the quest line is always hidden for some reason? 

To make matters worse the same options show up for individual quests as well as quest lines. 

I'm completely confused and have no idea how to use this feature. lol

Could you please explain it?

**Comment by Funwayguy** [comment]
Just to clarify, visibility settings don't apply when in edit mode (otherwise you wouldn't be able to see what you're editing). You'll need to toggle edit mode when you actually want to see it applied.

The quest line visibility is based on state of contained quest. Only if a quest meets or exceeds the visibility state will it be visible on the list. The rules are as follows:

- Normal: One or more quests are visible. They do not need to be unlocked.
- Unlocked: One or more quest are unlocked. Doesn't need to be visible.
- Completed: One or more quests have been completed. Doesn't need to be visible.
- Always: The quest line is always visible in the list regardless of the state of quests.
- Hidden: The quest line is never visible. Used primarily for hidden event triggers, etc.
- Chain: Behaves the same as normal. (This setting is meant more for individual quests)

Note: This only affects whether the button shows up on the list. It doesn't affect whether a player can actually open the quest line. That still follows the normal rule (because at least one quest needs to be visible anyway).

**Comment by Winddbourne** [comment]
Thank you. It looks like what I actually wanted to do isn't going to be
possible with these options and that saves me a lot of frustration thinking
I just don't get it. I was looking for an option that would let me hide
quest lines once they were completed so I could clean up my lists as the
player progresses.

In particular, I've got a starting quest line where the choices the player
makes determine which set of other quests open up for the rest of the pack.
They literally only use it once and never have to touch it again. I felt it
was silly to just leave it sitting there at the top of the list for the
rest of the game: "Congratulations! You made a choice." lol. I was going
crazy trying to figure out how to use completed or chain to hide the
thing.

**Comment by Funwayguy** [comment]
Sorry but revoking visibility of a questline isn't currently supported without some roundabout method. I seen people want choice quests but I think this would be the first I've heard anyone wanting that for quest lines.

**Comment by Winddbourne** [comment]
I'm surprised nobody has wanted the feature before. It seems like common sense that as I open up new quest lines I would also want to hide completed ones so that the player can easily see what they need to do without having to scroll through a bunch of areas that aren't useful to them. I hope the feature shows up in the future. :)
