### ISSUE TITLE
Client crashed on startup  (1.12.2)

### ISSUE THREAD

**Issue by Deloyar81** [Funwayguy/BetterQuesting#627]
**What happended?**

I updated 'BQ .299' to .305 and 'BQ - Standard Expansion .158' to .161 and then the client crashed with this [crashlog](https://pastebin.com/c498vYfd) on startup.
It pointed at NPC-Integration and Custom NPCs, so I disabled them. But the Client crashed again  with this [Crashlog](https://pastebin.com/cKwF0QAy).
Now it seems to be the RF-Expansion. I disabled it too and then the client started.

I rollbacked BQ to .300 and enabled the disabled mods to test if the crash would appear too. Yes, there is a crash ([crashlog](https://pastebin.com/9rQRY0tL)), but not the same.
I rollbacked BQ - Standard Expansion to .159 too and all was fine.

**Mods:**

Better Questing - 3.5.305
BQ -Standard - 3.4.161
BQ - NPC Integration - 3.4.32
BQ - Quest Book - 3.1.EXP_NET2
BQ - RF Expansion - 3.4.28

Custom NPC'S - 1.12.2(30Jan19)

Forge - 14.23.5.2838

**Comment by Funwayguy** [comment]
BQ 305 and SE 161 beta builds have had major networking rewrites and the other expansions have not yet been updated to support these changes. They won't be updated until I'm done with the ongoing beta branch of changes. Besides being marked as beta on Curse Forge, these changes and warnings were part of the recent change logs.

If you absolutely need those expansions in order to run your pack then I recommend sticking with BQ 300 and SE 159 builds as they are the most up to date versions that still have compatibility for them.
