### ISSUE TITLE
[Requesting help - Not a bug] Updating from 3.5.282 to 3.5.309 caused a crash.

### ISSUE THREAD

**Issue by Numpty-Clodpole** [Funwayguy/BetterQuesting#647]
So, I was using the modpack called "FTB Continuum" which contains Better Questing v3.5.282, and I wanted to update it to the most recent one. However, doing so caused it to crash: [crash-2019-09-04_05.25.00-client.txt](https://github.com/Funwayguy/BetterQuesting/files/3572850/crash-2019-09-04_05.25.00-client.txt)

`Caused by: java.lang.ClassNotFoundException: betterquesting.api.misc.IFactory`

I was wondering if there was something I could edit to make it function, but if not I'll return to the previous one.

**Comment by Numpty-Clodpole** [comment]
Well, due to lack of any help, I've just returned to the version supplied by the modpack. Maybe a future version will work better.

**Comment by Funwayguy** [comment]
This issue can be summed up in 3 points:

1) The issue is that you installed a work-in-progress beta version (It's even marked as such on Curse Forge) which currently only works with a few beta versions of the expansions. The error is actually the expansion trying to tell you that the base version isn't what it expects anymore.

2) If you're changing out mods or versions, especially with existing packs outside their intended design, you are responsible for checking these things.

3) I am already working on releasing new betas soon with code changes which _still_ wouldn't be compatible with older expansions that you have installed. 

PS: I stopped responding to these issues and "not helping" because people keep mixing and matching betas then complain that it's my fault things stopped working. I have more important things to be working on and these reports are getting quite frustrating lately.

**Comment by Numpty-Clodpole** [comment]
I realise it's a beta; I update everything to latest whenever it's available. Generally if there's an issue whilst loading a beta, I'm able to figure out what went wrong and resolve it myself. This time I wasn't, and decided to ask here to see what I could do to get it to function. 

Simply being told it is incompatible with what I'm using would have been enough, and I don't blame you for anything lol. The point of this thread was to ask a question, not report something or point fingers.

**Comment by balthild** [comment]
I've encountered the issue as well. I'm upgrading the mod from 3.5.282 to 3.5.300 -- both of witch are marked as release rather than beta on curseforge.

**Comment by balthild** [comment]
Sorry. I've confirmed that the issue is not caused by BQ itself.
