### ISSUE TITLE
Quests not functioning properly

### ISSUE THREAD

**Issue by ghost** [Funwayguy/BetterQuesting#653]
Issues with the current Beta release for BetterQuesting is the following:

- Quests don't always recognize items that you have in your inventory
- Quests assume that you have those items when you clearly don't
- Quests sometimes complete themselves despite not meeting all of the goals for them

![2019-09-19_12 57 23](https://user-images.githubusercontent.com/55064289/65264643-0fd8ba00-dadd-11e9-85ba-7ce261c2839e.png)
![2019-09-19_12 57 28](https://user-images.githubusercontent.com/55064289/65264644-0fd8ba00-dadd-11e9-946d-7f52bf9e1910.png)

**Comment by Funwayguy** [comment]
*looks at code*

Wow... okay so I accidentally inverted the detection logic. That was dumb. I'll go through the rest of the task types and see if I made similar mistakes before sending up a new build to Curse Forge

PS: Also turns out consume tasks eat everything _but_ the items you want starting from the hotbar. I don't think this build is safe to use anymore
