### ISSUE TITLE
Somehow running the updating quests command lets you crash after changing tot he newer version.

### ISSUE THREAD

**Issue by SirAron111** [Funwayguy/BetterQuesting#655]
Somehow running the updating quests command lets you crash after changing tot he newer version.

https://paste.dimdev.org/uleyiteril.mccrash
https://pastebin.com/kTSvrPRB

**Comment by Funwayguy** [comment]
I keep telling people to stop running that command as a "reward" because it can cause concurrency issues (reward is modifying the database that it's contained within). This is one such issue that happens.

If these variables are setup, users will be prompted with a flashing button to click and update safely without the concurrency issue. Besides that, I'm not going to "fix" this.

![image](https://user-images.githubusercontent.com/6048596/65814884-33ada580-e22b-11e9-9133-8c69baeda8f1.png)

**Comment by SirAron111** [comment]
O I didn’t even know about that. And since I did like from 1.0 to 9.2 of my Modpack already with no issue using it as a quest, I didn’t even think about it.

I will see to give players another way to use this command but in a survival world with no cheats allowed this could be a bit difficult. in case the button doesnt work well will see.

But thx for the info will try that.
