### ISSUE TITLE
Party Questing Not Syncd

### ISSUE THREAD

**Issue by MVethana** [Funwayguy/BetterQuesting#664]
Playing DDSS updated from 3.5.300 to 3.5.316 and quests no longer sync properly between parties. The /bq_user refresh command does not resolve the issue. Thanks

**Comment by Funwayguy** [comment]
Which quest types are you referring to?

Party sync was changed considerably in recent versions to fix players exploiting it to submit less items per player than those going solo.

**Comment by MVethana** [comment]
What do you mean by quest types? Since the update players on our server do not have completed quests syncing across parties. Ex. A player has a completed quest but another player in the party does not have the quest completed and asks for the player to detect the item.

**Comment by Funwayguy** [comment]
If it's a detect task then that should sync just fine but those players need to be online and in the party at the time of detection. You can't have offline people doing nothing, or new members earn progress they weren't present for.

General rule of thumb is that if the task requires consumption of resources then it's probably not going to be shared.

**Comment by MVethana** [comment]
I can guarantee that this was not an issue in previous versions for the detect task. As an example on the server I could come online even when my teammate was not online and any quests he had completed while I was offline would show as completed and allow me to claim the rewards. Every player on the server is saying this has become an issue since the update. Thanks

**Comment by Funwayguy** [comment]
That's because I changed it intentionally. People were exploiting it and freeloading off their parties while solo players got screwed over. This was my solution.

I can re-enable offline progression if necessary on select task types but I haven't seen a compelling argument as to why I should. I've explained this to a few pack devs, including Enigmatica's, and none have not had issue with this decision.

**Comment by MVethana** [comment]
What do you mean by exploiting? Are you referring to how parties get multiple sets of the rewards? Would it be possible to instead enable offline progression but once rewards are claimed once they cannot be claimed by another member of the party again? this would result in quests being syncd across parties but preventing parties from receiving extra rewards.

**Comment by AManNamed2** [comment]
Why not just make it an option? Far easier than just telling my bud to flip on edit mode in our party & unlocking the quests trying to sync up to me vs just always being synced

I understand people exploiting solo players or whatever but this now affects everyone no matter if they didn't mind their offline bud (different timezone) being offline when progressing

**Comment by DaveB63** [comment]
My team is in the same position - we cooperate on quests but we are spread over 6 timezones. We all contribute to achieving the goal, one started earlier than the others and laid some groundwork, everybody else joined in when their timezone overlapped and then it gets completed while only the later timezone folks are online. What are we supposed to do, cut our play time to just the few hours when we can all be on? 

At least make it a config option to the mod, so that players like me who are on a server that isn't competitive between teams and doesn't have an exploiter problem can leave offline sync enabled.

**Comment by sporefreak** [comment]
Me and my cousin play lan, and I often am at work while he plays, with the changes I am basically forced to do a lot of the consumption quests myself.
I understand the reasoning but I really wish it would be a config option that's default to true, otherwise you are punishing a ton of lan players or privste servers all of who will typically not have those problems with players and won't come here to ask for help.
Could the consumption quests which seem to be the problem be fixed if they required all the materials at once? I was not aware of the exploit and do not know how it works

**Comment by DGSitze** [comment]
Me and my cousin play lan, and I often am at work while he plays, with the changes I am basically forced to do a lot of the consumption quests myself.
I understand the reasoning but I really wish it would be a config option that's default to true, otherwise you are punishing a ton of lan players or privste servers all of who will typically not come here to ask for help.
Could the consumption quests which seem to be the problem be fixed if they required all the materials at once?

**Comment by Ishinyca** [comment]
Should make the offline sync a config. It's was really nice that I can progress through the quests while my other friends are offline. Now it's basically forcing everyone who has a life to get on at the same time to progress through quests. It is understandable to a degree how a party system can heavily effect solo players, but there other ways that can be done. This only applies to public servers that offline sync and multiple quest rewards shouldn't be a thing. But what's the point of being in a party if you can't quest together even with others are offline at the time? 

Modpack developers are fine with it from what it seems like, but what about the mass majority of the players who host their own private or lan servers? They should have a way to configure this "offline sync" or "multiple rewards" or not. It should be solely up to the server owners to config their own servers versus modpack developers.

It made some modpacks fun when playing privately with friends because of this offline sync. We all can log in at different times. We all can do our own things and still achieve a common goal especially with this offline sync. 

The only best option, in my opinion, is to add config options and letting server owners / players decide what they want. This will solve a lot of the issues that we have, including others, who have our personal lives to attend to or simply don't want to find time for everyone to get on.

**Comment by Madsens** [comment]
I have the exact same problem. We've been playing together, and enjoing going different ways, but completing quests in the same quest book. My friend rejoined the game after a few hours, and all the quests i completed in the meantime, were not completed in his questbook. So we can only play while we're both online. Version 3.5.316 installed.

This has completely ruined how we play the game, as we like to play together, in the same house, same achievements. Now he has to manually use the commands to complete quests if he rejoins after i complete quests, or the other way around. PLEASE enable us to offline sync again. The mod is awesome, but almost unplayable for us because of this.

**Comment by Funwayguy** [comment]
Offline progress share added in Standard Expansion 3.4.170. Config will be added at a later date (enabled by default for now)

Note: Change is not retroactive

**Comment by fabiantomischka** [comment]
Is there any way to use it on the normal one as well? Or can we exchange the mods for our pack just easily?

**Comment by ThaDaVos** [comment]
I don't know if this is mentioned but even when you're online they are not synced, if an item is picked up and then dropped to quickly it only triggers the quest for that player, not for the others -> had this a few times, also I think it has to be configurable (maybe from the Party screen for ease of use) because now it's just really nasty - I understand the change, but sometimes you can't be online and then telling my friends to not do any quests defeats the purpose of running the server -> is there any command or way to sync it up currently? (Yesterday I had to go through like 30 easy detect quests because they (2 people) had done them in the time I was offline for dinner)

**Comment by Funwayguy** [comment]
Pretty sure I fixed that in SE 3.4.171 after I was DMed about some weird sync behviour.

**Comment by ThaDaVos** [comment]
Maybe DD & SS  (Dungeons, Dragons and Space Shuttles) isn't updated yet, let me check

**Comment by ThaDaVos** [comment]
We've got 3.5.316 -> Maybe it got fixed after I updated yesterday, but before we had the problem (we we're on 6.4 [Beta Version])

**Comment by ThaDaVos** [comment]
I'll check next time I'm playing, yesterday I was an hour playing and only trying to get home after I met a dragon and then busy spawning in items to complete quests to get up to speed

**Comment by Funwayguy** [comment]
Base mod got updated to 3.5.317 too but that was just to fix the OSS not accepting piped fluids

**Comment by Kilazur** [comment]
This is a game breaking change. The only reason we power through the modpack with my friend is because we can split tasks, and not have to be online together to advance. Please make it configurable, preferably soon if you can.

**Comment by Quezler** [comment]
+1

**Comment by Funwayguy** [comment]
It may not be configurable yet but I have enabled offline sync already.

**Comment by GedasFX** [comment]
Playing DDSS v6.5 (BQ v3.5.317, SE v3.4.171) SP + LAN (so technically MP).

After reading your [comment](https://github.com/Funwayguy/BetterQuesting/issues/664#issuecomment-554842442), I can confirm weird syncing behavior definitely still exists. [Issue with slow updates](https://github.com/Funwayguy/BetterQuesting/issues/664#issuecomment-555460702) is still present, but only for the people connecting to the host. To prevent confusion, A - person, who has opened his SP world to LAN, B - a connecting person). 

- If A completes a quest, and he is not in an interface, it updates as good as instantly, and every other person takes a while to get updated. 
- If B completes a quest, and he is not in an interface, for A (not in interface) it also updates as good as instantly, but for the B person and other people on the server it takes a few seconds (EDIT: sometimes close to a minute) to update.

On top of that, we tested offline syncing (party leader is the one, who owns the SP world) and it just doesn't work. Manual `/bq_user refresh` does nothing to the world owner (not even a confirmation message) and generic "updated" to every other person (while also bearing 0 results). Obviously party leader will always be online, because if hes offline server will be off.

Do I have to set up something specific for this to work or is it just broken?

**Comment by GedasFX** [comment]
To clarify, it doesn't buffer quest completions. Example: a quests say: `detect 4 planks, and next quest is detect crafting table`. Person A crafts planks, detects and within 5 seconds makes a crafting table. Person B would not get crafting table quest completed, as planks have never been 'detected'.

All future quests after this will be out of sync, so it only takes 1 easy fast quest to break an entire chain of quests.

**Comment by jhutch1979** [comment]
I understand your reason for the change.  but for people like me who host a server for friends and we all join the same party this is a real drag.  If you were going to make such a major change like this I would expect a config option to be able to change it back.  otherwise I hope the major mod packs find a questing mod that will allow their server owners to play the way they want rather than one that forces you to play the way the mod creator thinks it should be.

**Comment by Funwayguy** [comment]
It's not really feasible to run two separate progression systems and attempt to hotswap them with a mere config. It's also unreasonable to ask for all 3rd party expansion developers to adhere to such demands and make their work equally harder.

This change was a long time coming and needed to be done one way or another. As much as I understand the concerns being expressed, I'm working with a much bigger picture than just a few friends on a private server. I need to account for hundreds of players, with thousands of quests made for many many different styles of packs. This also applies for commercial servers who have money involved in accessing their quests so 'harmless' exploits will simply not fly with those operators. A lot of this is already happening so it's not just an exaggeration.

Now yes offline syncing is currently broken and I am trying to fix it without breaking everything else in the process which is likely muddying what people think was and wasn't intentionally changed. It doesn't help that these bugs hit in the middle of a redesign. I can just release half baked GUIs for the sake of fixing something else.

I am but one person and this entire dev process post build 300 has been a big mess for me to juggle even if I knew it was coming. I am reading reports and people's concerns but it takes time especially when trying to avoid burnout.

Thankfully I am VERY close to a 318 build which should fix the offline syncing and bring a new chapter UI. So please just give me some more time to clean stuff up. If you find another questing mod that meets your needs then by all means feel free to switch (especially with 1.14 cause I am waaaay behind on that)

PS: I do have a public Discord server if you have questions you want to ask me directly or discuss other mod related topics. Link is on the BQ Curse Forge page

**Comment by Kimmiir88** [comment]
I cant seem to complete the mob farm quest in alpha even think have killed one of each mob and the /bq commands wont work. What can I do to fix this

**Comment by Penetrosity** [comment]
Thank you for considering and then planning to add this back. Me and my friends also always play with just a party on a team together working to get things done, and all the small friend groups I've joined has always done it this way, I recently just kinda 'fell off' playing Project Ozone 3 in particular because of this specific issue, it became a real hassle for us to put potentially good items away for the next player, or make more and store them in a box so people could complete and catch up when they jumped back on.

I understand that given how questing mods pretty much make or break these huge 'hardcore' questing backs there's a lot of pressure on you and a lot of people play on the big servers, those of us who don't and do like I or others here have said are probably not as widely heard, but I guarantee that any of us who have gone through packs where it's awful to work together because of things like this appreciate it when it's fixed or when party playing in those situations goes a lot closer to what we expect, even if it means we have to toggle a command (once per server) or change some config to get it that way.

**Comment by zaekeon** [comment]
Also posting here on the same concern.

  I have always played on servers with friends where the majority of the time we are all online but there are times where we are not due to work or one person having an extra day off that the other's do not.  

With this new system ii makes it incredibly frustrating to enjoy the game like we used to in the past.  We may be the minority but we always played the quest as a 'cooperative' effort especially on expert mode packs.  With the current system it feels like we are all playing a different game and the party doesn't provide much.

We appreciate the consideration to make it possible to revert the change or an option.  That would be awesome but I understand the complications on your side too.

**Comment by flocc** [comment]
Same here. Having an option to choose from would be really nice. Or give us at least some command to sync quests with party. Playing cooperative packs like Project Ozone 3 is PITA.

**Comment by axieum** [comment]
Can confirm, trying to complete PO3 in a 4 man squad, syncing up quests is not working half the time. Please add a configuration option to disable the exploit protection - thanks. This is not how a "party" works in my opinion.

**Comment by Funwayguy** [comment]
Last I checked, PO3 is running an old version with the party desync bug so what you're probably getting upset over isn't necessarily intended. Party invites were also pretty broken back then. Update 3.5.320 has fixed both these bugs as far as I'm aware and it's up to the pack devs at this point.

As I've mentioned before, I can't just add a config for that. Even if you personally disagree with how a party should or shouldn't work, a single opinions is not enough to warrant overturning the fair gameplay of thousands of other players.

Unless you have a legitimate bug with party desync (while using an up to date version mind you) there is no more need to leave this thread open.
