### ISSUE TITLE
New Layout

### ISSUE THREAD

**Issue by theshadowake** [Funwayguy/BetterQuesting#670]
Hey Funway, just testing out the new layout. You said in the change log you were looking for feedback :)

I must say in current form I'm not a huge fan, although I can see where you were going and can see the potential with changes.

I would maybe recommend releasing a version with the old visuals with the latest fixes just as an aside as there were some big issues with quest sync, but I don't feel the new layout is 'ready for mainstream' yet.

I'll try to provide as much 'constructive' feedback as I can. I don't want it to come off as me being too negative, just want to help improve the (fantastic) mod :)

1. Opening the quest book and it basically showing an empty page when you click quests doesn't seem like a good change, players not familiar with the layout will immediately think something is broken or that there are no quests. - To fix this I would probably have the 'bookmarks' tab auto open by default if nothing is already open.

2. On opening a quest page 'bookmark', the bookmarks list stays open half covering the screen, requiring an extra click to close it. This just seems unnecessary. - I would suggest having the list close on clicking an entry.

3. The 'info' tab for quest section being on a separate tab seems a bit disjointed, it was nice to have the info on the page so players could see it straight away. It was a great place to put crucial info to help players. It being on a separate tab feels like honestly they would never even bother using it, potentially missing that important information. - It would be nice to have this section as well as the info being on the page, maybe just as an area for pack makers to put large info as a separate thing?

Anyway that's about all I can think of right now. Keep up the good work 👍

**Comment by Funwayguy** [comment]
1) Easy fix. I can add that for next update but I'll just open the first available chapter instead of the tray

2) Also an easy fix. In fact this was how it behaved in dev for a short while (I got annoyed with the auto-close trying to flick through chapters) but I probably should have turned it back on for release.

3) This is a bit of a tricky one. The description box took up a lot of space for something that really only needs to be read once or twice. After that it's just wasted space. Sure it might contain useful info but that's only if a pack dev makes it so. Most of the time it's just flavour text.

If you really need a section for text info then I can make a dedicated library for it under the lore idea I have.

EDIT: Also just realised I forgot descriptive tooltips for the new sidebar buttons

**Comment by theshadowake** [comment]
1. Maybe the 'tray' icon could flash as well on first open? I think it would just be nice to have some kind of indicator to players that that's where the quests are hidden. Otherwise they may just think the 1 page is it (I like to work on the assumption that if something isn't blindingly obvious, there's a group of people who will miss it).
2. Cool 👍 
3. Yeah I agree it does look better for the quest side with way more space (I actually really like that idea). I just worry it would make that section redundant for 99% of players and as a pack dev I do find that 'tool' useful. Another option may be to have the quest tray/bookmark thing  with the list of quests, show that section to the right of it when hovering over a quest section, not sure how feasible that would be, but that would put the info in front of people when needed but leave the quest page itself free from clutter?

EDIT: Oh and yeah descriptive tooltips would be great 💯

**Comment by Funwayguy** [comment]
1
Good idea. Flashing can be added to the icon pretty easily so that's not a problem.

3
I get the concern but I can't make it a hover tooltip either. Large descriptions still need a dedicated panel to scroll through. This is why I just tucked it away in a tray. Another reason for moving it is where it was before was squashed and didn't allow for future proofing for embeds like images. If I could solve all of these things without sacrificing other content then I would but I don't have any good ideas on how.

**Comment by theshadowake** [comment]
Yeah I understand. Also embedded images would make my life lol. One simple thing I would suggest would be changing the icon then to more of an 'info' one e.g. i instead of the current ! Other than that keep up the good work, looking forward to future updates!

**Comment by Funwayguy** [comment]
I actually want to change the other icons too. The bookmark icon wasn't meant for chapters either and 'edit' doesn't have an icon so I've been using the gear for 'settings'. Planning on sorting that out once I overhaul the themes to match the new layout margins.

**Comment by Matrix0150** [comment]
If you're still open to more feedback, I'm playing on a pack with a lot of different quest category and it's really a pain to always open and closing the bookmark, would there be any way to keep it always open, but take less space (Essentially like before, I was really more a fan of the previous layout). I find it better to have more information at the same time, maybe as an option. Also now you only get the information of a completed quest when you open the bookmark.

Right now, I guess I could keep it open, but that make it so every time I open the book, I need to click quest, and then again need to click on the bookmark, which is small pain. Plus I cannot center the quest on the right, and there's a **lot** of empty space in the bookmark names.

https://i.imgur.com/zm9HDgn.png

**Comment by TInyTim917** [comment]
I would like to add a piece of feedback also. It would be really nice to "Lock" the bookmark in the out position, so it would be like the old way. The current is an extra click to open the bookmark.

**Comment by Funwayguy** [comment]
Hows this for locking it open? (clicking the sidebar button still works)

![hW7XYQf3yg](https://user-images.githubusercontent.com/6048596/71865721-6e3eac80-314f-11ea-9690-1be95864920f.gif)

Notes:

- The lock state is remembered if you close and open the GUI however it currently resets if you restart the entire game.
- This preview is using the newer SE themes and an alternative tray background texture that will be used as of next release.

**Comment by TInyTim917** [comment]
Look great!
If it is locked can you still navigate the quests on the right?

**Comment by martinjanas** [comment]
Im not fan of the new layout system.Please make the new layout system toggleable in config if its possible.

**Comment by Funwayguy** [comment]
It's not reasonable to maintain two separate UIs especially given the old one won't support anything new I add or may break entirely.

You can make suggestions on the new one but the old one isn't coming back.

**Comment by Slyklaw** [comment]
> * The lock state is remembered if you close and open the GUI however it currently resets if you restart the entire game.

Even when locked, every time you open the GUI, the Quest Lines pane is closed. Is there a way to always keep it open?

**Comment by luke-bravenboer** [comment]
> The lock state is remembered if you close and open the GUI however it currently resets if you restart the entire game.

+1 to what I'm guessing is what the previous comment is asking for- could we perhaps have an option to show the chapter list 'locked' open by default? It doesn't take up an obtrusive amount of screen space unless you're using a massive 'auto' view scale; on the contrary, it's definitely more useful to have it locked if you're switching between chapters often, and it's a little annoying to have to enable it every time I start the game.

I'm also concerned it might take new players a while to even discover & click on the Quest Lines button, so it would be preferable to enable it by default and give them the option to disable it instead. I've got my quest lines set up so the first few quests open up a few other quest chapters elsewhere, but now it's pretty unclear when new chapters get unlocked unless they already happen to have enabled the Lock Tray feature beforehand.

**Comment by Funwayguy** [comment]
Personally I'd rather people get used to using the trays because I intend to use them in more places over time, that's why it's setup this way. If it was locked in place like that when you opened it up the first place, few people would have noticed or adapted to the use of trays.

The issue of not being able to see when chapters get unlocked is something I want to address through other means like notification icons or other indicators. They're far more flexible (and language independent) than just jamming more things onto the button list.

**Comment by luke-bravenboer** [comment]
Sounds great, sounds like you've got other better ideas already then. Thanks for everything you do :+1:
