### ISSUE TITLE
Crashes after I open a certain part of the questbook

### ISSUE THREAD

**Issue by Blueberrypie255** [Funwayguy/BetterQuesting#768]
[crash-2023-03-14_20.47.24-client.txt](https://github.com/Funwayguy/BetterQuesting/files/10975824/crash-2023-03-14_20.47.24-client.txt)

When I open the "Transportation" Section of the questbook, it instantly crashes..

**Comment by Blueberrypie255** [comment]
I checked by testing the quests individually: Its a certain quest called "Rails"

**Comment by Funwayguy** [comment]
Quests used within BetterQuesting are written by the pack developers themselves and not by the mod developer. If I had to guess, the pack developers have written a quest involving a related item that does not render correctly outside of a normal inventory. Please report this to the pack developers detailing the quest you believe to be at fault.

**Comment by Blueberrypie255** [comment]
Im the pack dev

**Comment by Funwayguy** [comment]
In that case you will have to pick a different icon for that quest. BQ tries reasonably, but isn't able to contain every crash caused by quirky item rendering in other mods. If you can't remove the item icon from ingame but know the quest name you can open the JSON in the save directory and delete it there.
