### ISSUE TITLE
Crash on reading item NBT (1.7.10)

### ISSUE THREAD

**Issue by Zero-ui9** [Funwayguy/BetterQuesting#82]
http://pastebin.com/X5VGBCc6

Upon opening a quest with an ars magica spell as a reward, I get this crash. I'm assuming this is because ars magica spells are weird in that their NBT data contains int arrays, something not even handled by minecraft commands.

**Comment by Funwayguy** [comment]
I really need to look into how that mod's item NBTs are structured. This is the second time this crash has occurred and it's one last remaining edge cases BetterQuesting has issue with. I still believe the issue is on my side but ARS should probably not be performing unsafe casting with NBT data (other mods could trigger this same issue).

**Comment by Funwayguy** [comment]
Recently rewrote part of the NBT/JSON conversions which should hopefully kill this bug once and for all however any existing NBTs within quests will need re-saving for the new format to take effect.
