### ISSUE TITLE
quest data oddly formatted on update

### ISSUE THREAD

**Issue by ghost** [Funwayguy/BetterQuesting#92]
the data gets stuck in "betterquesting.placeholder"s as an object called "orig_data" which when reading the quests json contains all of the appropriate data one would expect it to other than it being encapsulated in that property. Is this some sort of automated format upgrade erroring out?

Luckily I have backups of my questing db files ;) and can confirm that the orig_data key was nonexistent in prior versions of my quest db. This seems to have been caused by upgrading to the newest beta which appears to be the default install choice when installing via curse as the newest beta release 2.0.175 crashes partway through loading as reported in #90's crash

**Comment by Funwayguy** [comment]
Placeholders are used when the task/reward types cannot be found or restored automatically. This is usually because an expansion is missing or the ID's formatting has been damaged though incorrect edits. The orig_data key will hold that data safely until the problem is resolved and the task/reward can be restored. This however can only be done in the new BQ2 builds as attempting to reload them in BQ1 will result in the data to be discarded as invalid.

The crashes you had earlier were because you were using BQ1 expansions with BQ2 builds. BQ2 was rewritten from the ground up and although it can load legacy quest databases, it cannot load legacy expansions.
